import UnlockMyWorld from '@/public/album/unlock_my_world.png';
import IveIve from '@/public/album/ive_ive.png';
import Expergo from '@/public/album/expergo.png';
import MyWorld from '@/public/album/my_world.png';

const IXVXStore: Music[] = [
  {
    id: 'menow',
    title: '#menow',
    group: 'fromis_9',
    album: UnlockMyWorld,
    session: [
      {
        id: 'f9_230608',
        title: 'M COUNTDOWN',
        date: '2023. 06. 08.',
        anchor: 34,
        videos: [
          { id: '12wE8piFkfo', type: 'main', anchor: 42.65 },
          { id: 'LZVVV0UkWHE', type: 'full', anchor: 37.07 },
          { id: 'pN4FKoKH1UY', type: 'single_full', member: 'Hayoung', anchor: 34.1 },
          { id: 'jryio89EE2k', type: 'single_full', member: 'Jisun', anchor: 34.17 },
          { id: '1iB4VufTZTo', type: 'single_full', member: 'Chaeyoung', anchor: 34.1 },
          { id: 'qygwNJjXODI', type: 'single_face', member: 'Nagyung', anchor: 35.95 },
          { id: 'ItQ_cE1nZ1Y', type: 'single_full', member: 'Nagyung', anchor: 34.14 },
          { id: 'Ldtx1Fq2XTw', type: 'single_face', member: 'Jihun', anchor: 36.1 },
          { id: 'uL5-y3NB9Gk', type: 'single_full', member: 'Jihun', anchor: 34.17 },
        ],
      },
      {
        id: 'f9_230609',
        title: 'Music Bank',
        date: '2023. 06. 09.',
        anchor: 34,
        videos: [
          { id: 'ygU0M8AoeAg', type: 'main', anchor: 40.78 },
          { id: 'Vf11ARSBYCw', type: 'full', anchor: 34.43 },
          { id: 'WUN6cjDXxnY', type: 'single_full', member: 'Saerom', anchor: 34.55 },
          { id: 'KGiIvjibTmQ', type: 'single_face', member: 'Hayoung', anchor: 41.59 },
          { id: 'pc3J0o_L0HY', type: 'single_full', member: 'Hayoung', anchor: 34.51 },
          { id: 'JVdorps9JuQ', type: 'single_full', member: 'Jiwon', anchor: 34.52 },
          { id: 'tkraDAyhiPg', type: 'single_full', member: 'Jisun', anchor: 34.49 },
          { id: '-7VgOH50Zm4', type: 'single_full', member: 'Seoyeon', anchor: 34.44 },
          { id: '4-elCfjQLp8', type: 'single_face', member: 'Chaeyeong', anchor: 34.2 },
          { id: '_58y-7QmHvw', type: 'single_full', member: 'Chaeyeong', anchor: 34.41 },
          { id: 'fnjyQzSja7o', type: 'single_face', member: 'Nagyung', anchor: 34.18 },
          { id: 'bQ2916lrN34', type: 'single_full', member: 'Nagyung', anchor: 34.58 },
          { id: 'SxuZJ9vPf9I', type: 'single_face', member: 'Jihun', anchor: 35.11 },
          { id: 'W3spS56XzQg', type: 'single_full', member: 'Jihun', anchor: 34.53 },
        ],
      },
      {
        id: 'f9_230611',
        title: 'Inkigayo',
        date: '2023. 6. 11.',
        anchor: 34,
        videos: [
          { id: 'fKaA7QNA8KM', type: 'main', anchor: 39.25 },
          { id: 'rh8QX9EGjwM', type: 'full', anchor: 42.76 },
          { id: 'llyuudJMJRI', type: '1take', anchor: 34.72 },
          { id: 'WHaxN0KHls8', type: 'single_full', member: 'Saerom', anchor: 38.35 },
          { id: 'cCKJ0yNW4Yg', type: 'single_full', member: 'Hayoung', anchor: 51.92 },
          { id: 'pJ4S4OpT4uw', type: 'single_face', member: 'Hayoung', anchor: 34.22 },
          { id: 'xeBR1dPtxXM', type: 'single_full', member: 'Jiwon', anchor: 41.2 },
          { id: '48BfU5nLchw', type: 'single_full', member: 'Jisun', anchor: 34.18 },
          { id: 'uCdqgYBjuFg', type: 'single_full', member: 'Seoyeon', anchor: 40.49 },
          { id: 'j97OscmKOmI', type: 'single_full', member: 'Chaeyoung', anchor: 34.2 },
          { id: '2ghWS9moAQg', type: 'single_face', member: 'Chaeyoung', anchor: 36.76 },
          { id: '3aSqJza7CJg', type: 'single_full', member: 'Nagyung', anchor: 45.13 },
          { id: 'I0yLI_QYmj0', type: 'single_face', member: 'Nagyung', anchor: 48.94 },
          { id: 'qffpeTS4bJA', type: 'single_full', member: 'Jihun', anchor: 49.47 },
          { id: '5OBwkVpnNFM', type: 'single_face', member: 'Jihun', anchor: 42.67 },
        ],
      },
      {
        id: 'f9_230614',
        title: 'Show Champion',
        date: '2023. 6. 14.',
        anchor: 34,
        videos: [
          { id: 'oqtLzpv9MDM', type: 'main', anchor: 45.52 },
          { id: 'Zr6w0m9hKeE', type: 'full', anchor: 35.09 },
          { id: 'IUtN6X7tEhg', type: 'single_full', member: 'Saerom', anchor: 35.1 },
          { id: 'DMMeBBvrQKo', type: 'single_full', member: 'Hayoung', anchor: 35.08 },
          { id: 'holBjxVWReU', type: 'single_full', member: 'Jiwon', anchor: 35.08 },
          { id: 'vwRcJViIBcw', type: 'single_full', member: 'Jisun', anchor: 35.08 },
          { id: 'FznfRjrPn3E', type: 'single_full', member: 'Seoyeon', anchor: 35.15 },
          { id: 'bNfIO_M0Djk', type: 'single_full', member: 'Chaeyoung', anchor: 35.09 },
          { id: '2SlQduAcJ6c', type: 'single_full', member: 'Nagyung', anchor: 35.07 },
          { id: 'Fu614M_0ns8', type: 'single_full', member: 'Jihun', anchor: 35.08 },
        ],
      },
      {
        id: 'f9_230618',
        title: 'Inkigayo',
        date: '2023. 6. 18.',
        anchor: 34,
        videos: [
          { id: 'MG1y6193q1w', type: 'main', anchor: 34.39 },
          { id: '1B0ecpXn0Vc', type: 'full', anchor: 33.91 },
          { id: '2WhEv4da0LI', type: 'single_face', member: 'Saerom', anchor: 54.64 },
          { id: 't5ZlGM5lcaY', type: 'single_face', member: 'Jiwon', anchor: 56.6 },
          { id: '_hNyFzZ2TPo', type: 'single_face', member: 'Jisun', anchor: 36.29 },
          { id: 'GGYyhIxPQ-o', type: 'single_face', member: 'Seoyeon', anchor: 46.07 },
          { id: 'lVtaM2ZsSWA', type: 'single_full', member: 'Nagyung', anchor: 33.13 },
          { id: 'T_ZoGeRCUBs', type: 'single_full', member: 'Jihun', anchor: 34.06 },
        ],
      },
    ],
  },
  {
    id: 'iam',
    title: 'I AM',
    group: 'IVE',
    album: IveIve,
    session: [
      {
        id: 'iv_230413',
        title: 'M COUNTDOWN',
        date: '2023. 4. 13.',
        anchor: 52,
        videos: [
          { id: 'dus7C4CTWUk', type: 'main', anchor: 61.64 },
          { id: 'FMZ5eA0a-VA', type: 'full', anchor: 103.8 },
          { id: 'EzB7hB8EaVU', type: 'single_full', member: 'Yujin', anchor: 54.47 },
          { id: 'g9AmSLZdVk8', type: 'single_face', member: 'Yujin', anchor: 52.06 },
          { id: 'JoYR_cQdsTQ', type: 'single_full', member: 'Gaeul', anchor: 54.44 },
          { id: '48yQAp5ra2w', type: 'single_face', member: 'Gaeul', anchor: 52.94 },
          { id: '9umB7Vp9bxY', type: 'single_full', member: 'Wonyoung', anchor: 54.43 },
          { id: 'cfRlXVNwV2E', type: 'single_face', member: 'Wonyoung', anchor: 95.2 },
          { id: 'PC0g2XTDZGc', type: 'single_full', member: 'Liz', anchor: 54.42 },
          { id: 'YgGPaTbUZCU', type: 'single_face', member: 'Liz', anchor: 54.69 },
          { id: '0izeq78RpHs', type: 'single_full', member: 'Leeseo', anchor: 54.42 },
          { id: 'WcxoyngF5wk', type: 'single_face', member: 'Leeseo', anchor: 53.13 },
        ],
      },
      {
        id: 'iv_230414',
        title: 'Music Bank',
        date: '2023. 4. 14.',
        anchor: 52,
        videos: [
          { id: 'el8QQFA3xKI', type: 'main', anchor: 59.88 },
          { id: 'BVf-pipXhN8', type: 'full', anchor: 51.8 },
          { id: 'o4uCQoG-2vE', type: '1take', anchor: 52.12 },
          { id: 'Jfm3z5IF9EY', type: 'single_full', member: 'Yujin', anchor: 52.09 },
          { id: 'pQXvySinRGU', type: 'single_face', member: 'Yujin', anchor: 52.32 },
          { id: '4A2wfok8U2E', type: 'single_full', member: 'Gaeul', anchor: 52.14 },
          { id: 'R-2_mKua8NA', type: 'single_face', member: 'Gaeul', anchor: 52.43 },
          { id: 'Ptdw-59QJ9k', type: 'single_full', member: 'Wonyoung', anchor: 52.1 },
          { id: 'LDNy2oJ22lM', type: 'single_face', member: 'Wonyoung', anchor: 51.76 },
          { id: 'BD4Ihmk2I2E', type: 'single_full', member: 'Liz', anchor: 52.22 },
          { id: 'a6hJf2iJ6jk', type: 'single_face', member: 'Liz', anchor: 52.45 },
          { id: '0If66frbJ78', type: 'single_full', member: 'Leeseo', anchor: 52.14 },
          { id: 'Ls1fhIiTxM4', type: 'single_face', member: 'Leeseo', anchor: 52.12 },
        ],
      },
      {
        id: 'iv_230415',
        title: 'Music Core',
        date: '2023. 4. 15.',
        anchor: 52,
        videos: [
          { id: 'XM78ZzK_dCM', type: 'main', anchor: 52.33 },
          { id: 'hXYaPEg8Pes', type: 'full', anchor: 53.1 },
          { id: '_TnFfJ_HCdI', type: 'single_full', member: 'Yujin', anchor: 53.97 },
          { id: '-LqZrSHRQ3E', type: 'single_face', member: 'Yujin', anchor: 52.57 },
          { id: 'vX66dsJBWlc', type: 'single_full', member: 'Gaeul', anchor: 52.21 },
          { id: 'eWOmgmR7kDs', type: 'single_face', member: 'Gaeul', anchor: 52.18 },
          { id: 'ZbfgiRfKE40', type: 'single_full', member: 'Wonyoung', anchor: 53.33 },
          { id: '06faE9OZ2ms', type: 'single_face', member: 'Wonyoung', anchor: 52.29 },
          { id: 'xzWtTxIgkyQ', type: 'single_full', member: 'Liz', anchor: 53.85 },
          { id: 'KjWRFTsf0bc', type: 'single_face', member: 'Liz', anchor: 52.09 },
          { id: 'XyLYx61AGsE', type: 'single_full', member: 'Leeseo', anchor: 52.82 },
          { id: 'eWeuPeJ1tY0', type: 'single_face', member: 'Leeseo', anchor: 52.89 },
        ],
      },
      {
        id: 'iv_230416',
        title: 'Inkigayo',
        date: '2023. 4. 16.',
        anchor: 52,
        videos: [
          { id: 'nnQddxQu2aU', type: 'main', anchor: 83.74 },
          { id: 'Z6SizsDLcrg', type: '1take', anchor: 52.16 },
          { id: 'SpLW2NcFsiY', type: 'tower', anchor: 52.54 },
          { id: 'zRHC7nYqxDk', type: 'full', anchor: 67.57 },
          { id: 'EtYWZzt3Iig', type: 'single_full', member: 'Yujin', anchor: 111.47 },
          { id: 'LKclCOjE1y4', type: 'single_face', member: 'Yujin', anchor: 81.42 },
          { id: '2ubER7dAra0', type: 'single_full', member: 'Gaeul', anchor: 73.8 },
          { id: 'COq08n8wl4k', type: 'single_face', member: 'Gaeul', anchor: 78.39 },
          { id: 'hzBt1AZcM2w', type: 'single_full', member: 'Wonyoung', anchor: 68.29 },
          { id: 'FBCR7eBuMNQ', type: 'single_face', member: 'Wonyoung', anchor: 67.64 },
          { id: 'yglwAIYeZnI', type: 'single_full', member: 'Liz', anchor: 70.62 },
          { id: '2n6eAHysdQU', type: 'single_face', member: 'Liz', anchor: 51.29 },
          { id: 'WqC8YK9ATqM', type: 'single_full', member: 'Leeseo', anchor: 92.01 },
          { id: 'iFo3dyxMjHY', type: 'single_face', member: 'Leeseo', anchor: 51.21 },
        ],
      },
      {
        id: 'iv_230420',
        title: 'M COUNTDOWN',
        date: '2023. 4. 20.',
        anchor: 52,
        videos: [
          { id: 'l4hf0JACcgU', type: 'main', anchor: 53.18 },
          { id: 'IjeDvs5PeYo', type: 'full', anchor: 52.24 },
          { id: 'KxCpYYwtQD4', type: 'single_full', member: 'Yujin', anchor: 51.25 },
          { id: 'kpKsvsAYJjA', type: 'single_face', member: 'Yujin', anchor: 52.06 },
          { id: 'gekN-tjcl4Y', type: 'single_full', member: 'Gaeul', anchor: 51.28 },
          { id: '8QBZn5-c6QQ', type: 'single_full', member: 'Wonyoung', anchor: 51.29 },
          { id: 'N9h8e8SHs_Q', type: 'single_face', member: 'Wonyoung', anchor: 51.91 },
          { id: '_7Lh3oMqdD4', type: 'single_full', member: 'Liz', anchor: 51.29 },
          { id: '0ZmrgdkP2nk', type: 'single_face', member: 'Liz', anchor: 52.49 },
          { id: 'uOBS2opNbwM', type: 'single_full', member: 'Leeseo', anchor: 51.33 },
        ],
      },
      {
        id: 'iv_230421',
        title: 'Music Bank',
        date: '2023. 4. 21.',
        anchor: 52,
        videos: [
          { id: '3s6l59R6jww', type: 'main', anchor: 65.72 },
          { id: 'GjoALzCN97s', type: 'full', anchor: 51.38 },
          { id: 'k_KuJoGjI4M', type: 'single_full', member: 'Yujin', anchor: 53.23 },
          { id: 'LzZeI__z47o', type: 'single_face', member: 'Yujin', anchor: 52.07 },
          { id: 'ULgmxEdT_w0', type: 'single_full', member: 'Gaeul', anchor: 53.29 },
          { id: 'oMkUcD3BH8c', type: 'single_full', member: 'Wonyoung', anchor: 53.24 },
          { id: 'Us9v3bJPK7Y', type: 'single_face', member: 'Wonyoung', anchor: 52.19 },
          { id: 'Z-CjQdbHcMo', type: 'single_full', member: 'Liz', anchor: 53.28 },
          { id: 'bDleRllukgM', type: 'single_full', member: 'Leeseo', anchor: 53.31 },
        ],
      },
      {
        id: 'iv_230422',
        title: 'Music Core',
        date: '2023. 4. 22.',
        anchor: 52,
        videos: [
          { id: 'vMXGX4Dp3iM', type: 'main', anchor: 52.54 },
          { id: 'UmQdkzFW02o', type: 'full', anchor: 52.38 },
          { id: 'hSKmLcdsjjQ', type: 'single_full', member: 'Yujin', anchor: 50.33 },
          { id: 'ocDBnUx3sK4', type: 'single_face', member: 'Yujin', anchor: 52.18 },
          { id: 'dKEqtJZgldM', type: 'single_full', member: 'Gaeul', anchor: 52.42 },
          { id: '-9hftESKRj0', type: 'single_face', member: 'Gaeul', anchor: 52.08 },
          { id: 'Ob5duBuI6I0', type: 'single_full', member: 'Wonyoung', anchor: 51.91 },
          { id: 'KEcWVoouaZU', type: 'single_face', member: 'Wonyoung', anchor: 52.2 },
          { id: 'dIPxPZNL4rc', type: 'single_full', member: 'Liz', anchor: 52.54 },
          { id: 'AqfR7lN6LMg', type: 'single_face', member: 'Liz', anchor: 52.13 },
          { id: 'cpvWYJEU9i0', type: 'single_full', member: 'Leeseo', anchor: 52.09 },
          { id: 'dqLuPzl5M7k', type: 'single_face', member: 'Leeseo', anchor: 54.26 },
        ],
      },
      {
        id: 'iv_230423',
        title: 'Inkigayo',
        date: '2023. 4. 23.',
        anchor: 52,
        videos: [
          { id: 'i6aSKcYwtMY', type: 'main', anchor: 54.19 },
          { id: 'O-4e_BCphSw', type: 'full', anchor: 52.08 },
          { id: 'n4_JPmceeNQ', type: 'single_full', member: 'Yujin', anchor: 53.69 },
          { id: 'CAqjHvMTFFw', type: 'single_full', member: 'Gaeul', anchor: 52.21 },
          { id: '-upaPSCKQeg', type: 'single_full', member: 'Wonyoung', anchor: 52.03 },
          { id: '45v7qN_aInI', type: 'single_face', member: 'Wonyoung', anchor: 52.06 },
          { id: 'Whsq-NxScdc', type: 'single_full', member: 'Liz', anchor: 52 },
          { id: 'vXCjn3u54b4', type: 'single_face', member: 'Liz', anchor: 51.96 },
          { id: 'J-TsdSiOn8Y', type: 'single_full', member: 'Leeseo', anchor: 52.07 },
          { id: '6gK9nQ2OGIA', type: 'single_face', member: 'Leeseo', anchor: 51.93 },
        ],
      },
    ],
  },
  {
    id: 'lovemelikethis',
    title: 'Love Me Like This',
    group: 'NMIXX',
    album: Expergo,
    session: [
      {
        id: 'nm_230323',
        title: 'M COUNTDOWN',
        date: '2023. 3. 23.',
        anchor: 56,
        videos: [
          { id: 'g1UNai7vSPk', type: 'main', anchor: 63.89 },
          { id: 'zJcPaVjVRNo', type: 'full', anchor: 58.7 },
          { id: '2hsNDr0QWNg', type: 'single_full', member: 'Lily', anchor: 58.69 },
          { id: 'th3QPuXlVxM', type: 'single_full', member: 'Haewon', anchor: 58.67 },
          { id: 'nuQ4NHeuSZg', type: 'single_full', member: 'Sullyoon', anchor: 58.67 },
          { id: 'ap8MFdfCTy8', type: 'single_full', member: 'Bae', anchor: 58.67 },
          { id: 'S9800GcCTco', type: 'single_full', member: 'Jiwoo', anchor: 58.68 },
          { id: '_taZJKjNCew', type: 'single_full', member: 'Kyujin', anchor: 58.71 },
        ],
      },
      {
        id: 'nm_230324',
        title: 'Music Bank',
        date: '2023. 3. 24.',
        anchor: 56,
        videos: [
          { id: 'uZQmVZxkPac', type: 'main', anchor: 63.3 },
          { id: 'vQV-m0jDH_A', type: '1take', anchor: 55.77 },
          { id: 'rDt63yhoIH8', type: 'full', anchor: 55.81 },
          { id: 'YVnGvX8eprQ', type: 'single_full', member: 'Lily', anchor: 55.72 },
          { id: 'KFDRy9979Cs', type: 'single_face', member: 'Lily', anchor: 55.48 },
          { id: 'i8_D-5ZkGIc', type: 'single_full', member: 'Haewon', anchor: 55.73 },
          { id: 'ym4ZdDuQt74', type: 'single_face', member: 'Haewon', anchor: 55.82 },
          { id: 'QhNFEPPC_YM', type: 'single_full', member: 'Sullyoon', anchor: 55.74 },
          { id: 'm2E_5U2ZPtQ', type: 'single_face', member: 'Sullyoon', anchor: 55.79 },
          { id: 'aDBqvyiCfHk', type: 'single_full', member: 'Bae', anchor: 55.73 },
          { id: 'nGMLKGPdqZA', type: 'single_face', member: 'Bae', anchor: 55.73 },
          { id: 'RUettmMX8Co', type: 'single_full', member: 'Jiwoo', anchor: 55.73 },
          { id: 'AsAVwaVwDCI', type: 'single_face', member: 'Jiwoo', anchor: 55.78 },
          { id: 'Rv72z91oTTE', type: 'single_full', member: 'Kyujin', anchor: 55.73 },
          { id: 'yM4EGbUUZuw', type: 'single_face', member: 'Kyujin', anchor: 57.44 },
        ],
      },
      {
        id: 'nm_230325',
        title: 'Music Core',
        date: '2023. 3. 25.',
        anchor: 56,
        videos: [
          { id: 'ntBglmH_Hok', type: 'main', anchor: 55.72 },
          { id: '_33bSZ6h_1A', type: 'full', anchor: 55.97 },
          { id: 'e4zmiVRgHuE', type: 'single_full', member: 'Lily', anchor: 58.41 },
          { id: 'gwaKIkD5uZ0', type: 'single_full', member: 'Haewon', anchor: 56.05 },
          { id: 'lqht3KrQga0', type: 'single_face', member: 'Haewon', anchor: 55.8 },
          { id: '6Pv8tjyx22w', type: 'single_full', member: 'Sullyoon', anchor: 55.8 },
          { id: 'XzW1dMAcv-k', type: 'single_face', member: 'Sullyoon', anchor: 55.82 },
          { id: 'v1iPeohKoKg', type: 'single_full', member: 'Bae', anchor: 57.58 },
          { id: 'Ag4L2BUNb-4', type: 'single_face', member: 'Bae', anchor: 56.17 },
          { id: 'nptNrTV85ro', type: 'single_full', member: 'Jiwoo', anchor: 56.51 },
          { id: '9JO1Cz4fqwY', type: 'single_full', member: 'Kyujin', anchor: 56.35 },
        ],
      },
      {
        id: 'nm_230326',
        title: 'Inkigayo',
        date: '2023. 3. 26.',
        anchor: 56,
        videos: [
          { id: 'fy3z55uTBVk', type: 'main', anchor: 60.9 },
          { id: 'mGRq39_OO-I', type: 'full', anchor: 55.98 },
          { id: 'HiGRMuGNe1c', type: 'tower', anchor: 56.64 },
          { id: 'S5-asFuzJUA', type: 'single_full', member: 'Lily', anchor: 57.88 },
          { id: 'EWrLWV2W3sM', type: 'single_full', member: 'Haewon', anchor: 56.06 },
          { id: 'm9lLWqdEAV0', type: 'single_full', member: 'Sullyoon', anchor: 78.29 },
          { id: 'bnNHyTs_qzI', type: 'single_full', member: 'Bae', anchor: 65.91 },
          { id: 'OIUSUqdx3gs', type: 'single_full', member: 'Jiwoo', anchor: 57.95 },
          { id: 'eXYWF-J4f1M', type: 'single_full', member: 'Kyujin', anchor: 64.36 },
        ],
      },
      {
        id: 'nm_230329',
        title: 'Show Champion',
        date: '2023. 3. 29.',
        anchor: 56,
        videos: [
          { id: 'GeenXykTujo', type: 'main', anchor: 56.33 },
          { id: 'UIDAoDXkQzA', type: 'full', anchor: 56.64 },
          { id: 'atJeVSgn5DI', type: 'single_full', member: 'Lily', anchor: 56.64 },
          { id: 'rq2XQYbYTSM', type: 'single_full', member: 'Haewon', anchor: 56.61 },
          { id: '6IjCoBPfm7I', type: 'single_full', member: 'Sullyoon', anchor: 56.63 },
          { id: '2Bc5Ksr4LT8', type: 'single_full', member: 'Bae', anchor: 56.62 },
          { id: 'ly7SSYASVmQ', type: 'single_full', member: 'Jiwoo', anchor: 56.65 },
          { id: 'JgvCD0yScdQ', type: 'single_full', member: 'Kyujin', anchor: 56.67 },
        ],
      },
      {
        id: 'nm_230331',
        title: 'Music Bank',
        date: '2023. 3. 31.',
        anchor: 56,
        videos: [
          { id: '5QSwkSSt0jc', type: 'main', anchor: 70.43 },
          { id: 'sJRsHFt7a5U', type: 'full', anchor: 55.79 },
          { id: 'Qa3UJFUQt88', type: 'single_full', member: 'Lily', anchor: 58.05 },
          { id: 'yLBCnKPnI6A', type: 'single_full', member: 'Haewon', anchor: 58.05 },
          { id: 'gxZcTHTi1fU', type: 'single_full', member: 'Sullyoon', anchor: 58.06 },
          { id: 'nmmmU3qgWtI', type: 'single_face', member: 'Sullyoon', anchor: 56.12 },
          { id: 'ZCLHvlgQIRg', type: 'single_full', member: 'Bae', anchor: 57.99 },
          { id: '-hSsloLq5mY', type: 'single_full', member: 'Jiwoo', anchor: 58.02 },
          { id: 'bFtQjb-I5Mw', type: 'single_full', member: 'Kyujin', anchor: 58.06 },
          { id: 'gwGT48Xs9ak', type: 'single_face', member: 'Kyujin', anchor: 56.38 },
        ],
      },
      {
        id: 'nm_230402',
        title: 'Inkigayo',
        date: '2023. 4. 2.',
        anchor: 56,
        videos: [
          { id: 'VWHaz8n8eq0', type: 'main', anchor: 55.93 },
          { id: '7nsaMbXahx4', type: 'full', anchor: 56.13 },
          { id: 'd9oCxpBV0-w', type: 'single_full', member: 'Lily', anchor: 59.92 },
          { id: 'bmk6cRAE8lc', type: 'single_full', member: 'Haewon', anchor: 66.02 },
          { id: 'KLzc5TUnnK4', type: 'single_face', member: 'Haewon', anchor: 78.26 },
          { id: 'q0F0hrpHxdo', type: 'single_full', member: 'Sullyoon', anchor: 55.9 },
          { id: 'MigXDvkcVoM', type: 'single_face', member: 'Sullyoon', anchor: 75.06 },
          { id: 'jr8XznHNZ9Q', type: 'single_full', member: 'Bae', anchor: 56.01 },
          { id: 'etInrIOjZJ4', type: 'single_full', member: 'Jiwoo', anchor: 67.54 },
          { id: 't7buifTVLn4', type: 'single_face', member: 'Jiwoo', anchor: 59.91 },
          { id: 'VSiH6uJ0Sgo', type: 'single_full', member: 'Kyujin', anchor: 62.8 },
        ],
      },
      {
        id: 'nm_230412',
        title: 'Show Champion',
        date: '2023. 4. 12.',
        anchor: 56,
        videos: [
          { id: 'z0Mga1b_NNI', type: 'main', anchor: 67.9 },
          { id: 'PcQZq_zDNwU', type: 'full', anchor: 56.71 },
          { id: 'hRZ61s3gFPE', type: 'single_full', member: 'Lily', anchor: 56.68 },
          { id: 'BHTE30giMoE', type: 'single_full', member: 'Haewon', anchor: 56.71 },
          { id: 'J6sJubY9yL8', type: 'single_full', member: 'Sullyoon', anchor: 56.72 },
          { id: '2YKzF-fdChQ', type: 'single_full', member: 'Bae', anchor: 56.72 },
          { id: 'pFutUyRXFN8', type: 'single_full', member: 'Jiwoo', anchor: 56.7 },
          { id: '6CxeKIJyf5A', type: 'single_full', member: 'Kyujin', anchor: 56.72 },
        ],
      },
    ],
  },
  {
    id: 'spicy',
    title: 'Spicy',
    group: 'aespa',
    album: MyWorld,
    session: [
      {
        id: 'ae_230511',
        title: 'M COUNTDOWN',
        date: '2023. 5. 11.',
        anchor: 44,
        videos: [
          { id: 'k75oGRMiENk', type: 'main', anchor: 78.85 },
          { id: 'jGUXqgH1xvc', type: 'full', anchor: 52.2 },
          { id: 'EX2Q6QTjnsY', type: 'single_full', member: 'Karina', anchor: 45.23 },
          { id: 'kpEbQOzJb00', type: 'single_face', member: 'Karina', anchor: 45.87 },
          { id: 'serGk772VsI', type: 'single_full', member: 'Giselle', anchor: 45.26 },
          { id: '0NoxT6iAJy8', type: 'single_face', member: 'Giselle', anchor: 44.9 },
          { id: '3Ze1041sM7k', type: 'single_full', member: 'Winter', anchor: 45.27 },
          { id: 'em1zsb5OKXM', type: 'single_face', member: 'Winter', anchor: 58.98 },
          { id: '0dyExB3TxlY', type: 'single_full', member: 'Ningning', anchor: 50.79 },
          { id: '5a2NxXWfEks', type: 'single_face', member: 'Ningning', anchor: 44.6 },
        ],
      },
      {
        id: 'ae_230512',
        title: 'Music Bank',
        date: '2023. 5. 12.',
        anchor: 44,
        videos: [
          { id: 'H1c06ycRWaM', type: 'main', anchor: 70.43 },
          { id: 'xWyeg5qYL2I', type: 'full', anchor: 43.52 },
          { id: 'HeF2JRgznOs', type: 'single_full', member: 'Karina', anchor: 44.4 },
          { id: '68thnf9uKUU', type: 'single_face', member: 'Karina', anchor: 43.83 },
          { id: 'FojJBz4LqhY', type: 'single_full', member: 'Giselle', anchor: 44.41 },
          { id: 'pjHxO267AYk', type: 'single_face', member: 'Giselle', anchor: 44.22 },
          { id: '2H2h6ODDbN4', type: 'single_full', member: 'Winter', anchor: 44.4 },
          { id: 'FPvCy4YxZ0w', type: 'single_face', member: 'Winter', anchor: 70.41 },
          { id: 'diPDMNxCoGY', type: 'single_full', member: 'Ningning', anchor: 44.37 },
          { id: '0M-rQwyfIXc', type: 'single_face', member: 'Ningning', anchor: 44.66 },
        ],
      },
      {
        id: 'ae_230513',
        title: 'Music Core',
        date: '2023. 5. 13.',
        anchor: 44,
        videos: [
          { id: 'dJ09BiaovoU', type: 'main', anchor: 44.32 },
          { id: 'NRvqGh6nGWA', type: 'full', anchor: 44.88 },
          { id: 'mO0oHjAnA0A', type: 'single_full', member: 'Karina', anchor: 44.2 },
          { id: 'fswJ9kgKvrY', type: 'single_face', member: 'Karina', anchor: 44.12 },
          { id: 'nDv5t-CiMEw', type: 'single_full', member: 'Giselle', anchor: 44.59 },
          { id: 'g667CEcJy84', type: 'single_face', member: 'Giselle', anchor: 44.95 },
          { id: 'cQ48GtBfqAo', type: 'single_full', member: 'Winter', anchor: 44.52 },
          { id: 'lohKfGOWsSc', type: 'single_face', member: 'Winter', anchor: 46.86 },
          { id: 'RJJ497BQhmI', type: 'single_full', member: 'Ningning', anchor: 44.84 },
          { id: 'WuvBFSkeKsE', type: 'single_face', member: 'Ningning', anchor: 44.46 },
        ],
      },
      {
        id: 'ae_230514',
        title: 'Inkigayo',
        date: '2023. 5. 14.',
        anchor: 44,
        videos: [
          { id: 'FsvzDcfvCW0', type: 'main', anchor: 48.95 },
          { id: '2Fm25bf4fjw', type: 'tower', anchor: 47.44 },
          { id: 'tX3G0yzQqD4', type: '1take', anchor: 46.22 },
          { id: 'Wrw2un78CQs', type: 'full', anchor: 43.92 },
          { id: 'cskrzMWLCms', type: 'single_full', member: 'Karina', anchor: 44.12 },
          { id: 'gpFSXXhonVk', type: 'single_face', member: 'Karina', anchor: 44.32 },
          { id: '21YjIg3XMN0', type: 'single_full', member: 'Giselle', anchor: 44.01 },
          { id: 'a1BF2BBXE2g', type: 'single_face', member: 'Giselle', anchor: 44.39 },
          { id: 'NnUwY5jcrBc', type: 'single_full', member: 'Winter', anchor: 43.96 },
          { id: 'Upc8cmpQNbk', type: 'single_face', member: 'Winter', anchor: 51.14 },
          { id: 'sRPi_lMHUPY', type: 'single_full', member: 'Ningning', anchor: 43.99 },
          { id: '_0ogBPpOaFY', type: 'single_face', member: 'Ningning', anchor: 43.98 },
        ],
      },
      {
        id: 'ae_230518',
        title: 'M COUNTDOWN',
        date: '2023. 5. 18.',
        anchor: 44,
        videos: [
          { id: 'RzeFY37-Mak', type: 'main', anchor: 43.91 },
          { id: 'XbTyYsOUfjE', type: 'full', anchor: 44.11 },
          { id: 'edHydgKcCwQ', type: 'live', anchor: 135.01 },
          { id: 'mQNNCYONyd4', type: 'single_full', member: 'Karina', anchor: 48.19 },
          { id: 'yWm4PtbdxUA', type: 'single_face', member: 'Karina', anchor: 42.45 },
          { id: 'xVR-aHFQTUg', type: 'single_full', member: 'Giselle', anchor: 48.22 },
          { id: 'py_lZZuGucw', type: 'single_full', member: 'Winter', anchor: 48.21 },
          { id: 'RG0PCA8UMIw', type: 'single_full', member: 'Ningning', anchor: 48.18 },
        ],
      },
      {
        id: 'ae_230519',
        title: 'Music Bank',
        date: '2023. 5. 19.',
        videos: [
          { id: 'qKzbdCkRjfA', type: 'main', anchor: 52.5 },
          { id: 'cZDO5oXQHbk', type: 'full', anchor: 44.33 },
          { id: 'qNBWD3FxB8U', type: 'live', anchor: 128.9 },
          { id: 'qehyXtfAjBk', type: 'single_full', member: 'Karina', anchor: 44.32 },
          { id: 'TqBXWlVKXrs', type: 'single_face', member: 'Karina', anchor: 44.61 },
          { id: 'yxiDNkyd3Fs', type: 'single_full', member: 'Giselle', anchor: 44.4 },
          { id: 'VFevjdi5s9w', type: 'single_face', member: 'Giselle', anchor: 44.12 },
          { id: 'pewqJxdVG4E', type: 'single_full', member: 'Winter', anchor: 44.35 },
          { id: 'ETZahO-oHXc', type: 'single_face', member: 'Winter', anchor: 44.15 },
          { id: '4Jhb1W-jcAk', type: 'single_full', member: 'Ningning', anchor: 44.33 },
          { id: 'mmpIGk_zD-o', type: 'single_face', member: 'Ningning', anchor: 44 },
        ],
      },
      {
        id: 'ae_230520',
        title: 'Music Core',
        date: '2023. 5. 20.',
        anchor: 44,
        videos: [
          { id: 'xq7L0A1657I', type: 'main', anchor: 44.23 },
          { id: 'ffJ7suIEM6k', type: 'live', anchor: 112.03 },
          { id: '3pmaDofPC4c', type: 'full', anchor: 44.29 },
          { id: 'CQTe26dANK4', type: 'single_full', member: 'Karina', anchor: 43.9 },
          { id: 'PZRe_Syi2pY', type: 'single_face', member: 'Karina', anchor: 43.93 },
          { id: 'rZ1-jE6qeTI', type: 'single_full', member: 'Giselle', anchor: 44.25 },
          { id: '_2XPrCD8TaY', type: 'single_face', member: 'Giselle', anchor: 45.15 },
          { id: 'noV57PLcvKg', type: 'single_full', member: 'Winter', anchor: 44.03 },
          { id: '2lbTFJi91z8', type: 'single_face', member: 'Winter', anchor: 44.23 },
          { id: 'v06p_YioTf8', type: 'single_full', member: 'Ningning', anchor: 44.65 },
          { id: '8TP3ykBJbm0', type: 'single_face', member: 'Ningning', anchor: 53.98 },
        ],
      },
      {
        id: 'ae_230521',
        title: 'Inkigayo',
        date: '2023. 5. 21.',
        anchor: 44,
        videos: [
          { id: 'rC4McQfRCBA', type: 'main', anchor: 44.02 },
          { id: 'ghFFHNUsvEM', type: 'live', anchor: 95.8 },
          { id: 'vr4usgQNfUM', type: 'full', anchor: 43.91 },
          { id: '6cWRzhHebqM', type: 'single_full', member: 'Karina', anchor: 43.91 },
          { id: '5ErG8C-f_LQ', type: 'single_face', member: 'Karina', anchor: 66.77 },
          { id: 'OJjMP5GQyd4', type: 'single_full', member: 'Giselle', anchor: 62.02 },
          { id: 'Vbh2wrYJjPQ', type: 'single_face', member: 'Giselle', anchor: 43.93 },
          { id: 'RGOGEKvHRBY', type: 'single_full', member: 'Winter', anchor: 60.83 },
          { id: 'KdFdSj6XxbA', type: 'single_face', member: 'Winter', anchor: 58.35 },
          { id: 'HsaOeu7Hkt0', type: 'single_full', member: 'Ningning', anchor: 43.98 },
          { id: '77iyTi75pXc', type: 'single_face', member: 'Ningning', anchor: 43.95 },
        ],
      },
    ],
  },
];

export default IXVXStore;
