import UnlockMyWorld from '@/public/album/unlock_my_world.png';
import IveIve from '@/public/album/ive_ive.png';

const IXVXStore: Music[] = [
  {
    id: 'menow',
    title: '#menow',
    group: 'fromis_9',
    album: UnlockMyWorld,
    session: [
      {
        id: 'f9_230608',
        title: 'M COUNTDOWN',
        date: '2023. 06. 08.',
        anchor: 34,
        videos: [
          { id: '12wE8piFkfo', type: 'main', anchor: 42.65 },
          { id: 'LZVVV0UkWHE', type: 'full', anchor: 37.07 },
          { id: 'pN4FKoKH1UY', type: 'single_full', member: 'Hayoung', anchor: 34.1 },
          { id: 'jryio89EE2k', type: 'single_full', member: 'Jisun', anchor: 34.17 },
          { id: '1iB4VufTZTo', type: 'single_full', member: 'Chaeyoung', anchor: 34.1 },
          { id: 'qygwNJjXODI', type: 'single_face', member: 'Nagyung', anchor: 35.95 },
          { id: 'ItQ_cE1nZ1Y', type: 'single_full', member: 'Nagyung', anchor: 34.14 },
          { id: 'Ldtx1Fq2XTw', type: 'single_face', member: 'Jihun', anchor: 36.1 },
          { id: 'uL5-y3NB9Gk', type: 'single_full', member: 'Jihun', anchor: 34.17 },
        ],
      },
      {
        id: 'f9_230609',
        title: 'Music Bank',
        date: '2023. 06. 09.',
        anchor: 34,
        videos: [
          { id: 'ygU0M8AoeAg', type: 'main', anchor: 40.78 },
          { id: 'Vf11ARSBYCw', type: 'full', anchor: 34.43 },
          { id: 'WUN6cjDXxnY', type: 'single_full', member: 'Saerom', anchor: 34.55 },
          { id: 'KGiIvjibTmQ', type: 'single_face', member: 'Hayoung', anchor: 41.59 },
          { id: 'pc3J0o_L0HY', type: 'single_full', member: 'Hayoung', anchor: 34.51 },
          { id: 'JVdorps9JuQ', type: 'single_full', member: 'Jiwon', anchor: 34.52 },
          { id: 'tkraDAyhiPg', type: 'single_full', member: 'Jisun', anchor: 34.49 },
          { id: '-7VgOH50Zm4', type: 'single_full', member: 'Seoyeon', anchor: 34.44 },
          { id: '4-elCfjQLp8', type: 'single_face', member: 'Chaeyeong', anchor: 34.2 },
          { id: '_58y-7QmHvw', type: 'single_full', member: 'Chaeyeong', anchor: 34.41 },
          { id: 'fnjyQzSja7o', type: 'single_face', member: 'Nagyung', anchor: 34.18 },
          { id: 'bQ2916lrN34', type: 'single_full', member: 'Nagyung', anchor: 34.58 },
          { id: 'SxuZJ9vPf9I', type: 'single_face', member: 'Jihun', anchor: 35.11 },
          { id: 'W3spS56XzQg', type: 'single_full', member: 'Jihun', anchor: 34.53 },
        ],
      },
      {
        id: 'f9_230611',
        title: 'Inkigayo',
        date: '2023. 6. 11.',
        anchor: 34,
        videos: [
          { id: 'fKaA7QNA8KM', type: 'main', anchor: 39.25 },
          { id: 'rh8QX9EGjwM', type: 'full', anchor: 42.76 },
          { id: 'llyuudJMJRI', type: '1take', anchor: 34.72 },
          { id: 'WHaxN0KHls8', type: 'single_full', member: 'Saerom', anchor: 38.35 },
          { id: 'cCKJ0yNW4Yg', type: 'single_full', member: 'Hayoung', anchor: 51.92 },
          { id: 'pJ4S4OpT4uw', type: 'single_face', member: 'Hayoung', anchor: 34.22 },
          { id: 'xeBR1dPtxXM', type: 'single_full', member: 'Jiwon', anchor: 41.2 },
          { id: '48BfU5nLchw', type: 'single_full', member: 'Jisun', anchor: 34.18 },
          { id: 'uCdqgYBjuFg', type: 'single_full', member: 'Seoyeon', anchor: 40.49 },
          { id: 'j97OscmKOmI', type: 'single_full', member: 'Chaeyoung', anchor: 34.2 },
          { id: '2ghWS9moAQg', type: 'single_face', member: 'Chaeyoung', anchor: 36.76 },
          { id: '3aSqJza7CJg', type: 'single_full', member: 'Nagyung', anchor: 45.13 },
          { id: 'I0yLI_QYmj0', type: 'single_face', member: 'Nagyung', anchor: 48.94 },
          { id: 'qffpeTS4bJA', type: 'single_full', member: 'Jihun', anchor: 49.47 },
          { id: '5OBwkVpnNFM', type: 'single_face', member: 'Jihun', anchor: 42.67 },
        ],
      },
      {
        id: 'f9_230614',
        title: 'Show Champion',
        date: '2023. 6. 14.',
        anchor: 34,
        videos: [
          { id: 'oqtLzpv9MDM', type: 'main', anchor: 45.52 },
          { id: 'Zr6w0m9hKeE', type: 'full', anchor: 35.09 },
          { id: 'IUtN6X7tEhg', type: 'single_full', member: 'Saerom', anchor: 35.1 },
          { id: 'DMMeBBvrQKo', type: 'single_full', member: 'Hayoung', anchor: 35.08 },
          { id: 'holBjxVWReU', type: 'single_full', member: 'Jiwon', anchor: 35.08 },
          { id: 'vwRcJViIBcw', type: 'single_full', member: 'Jisun', anchor: 35.08 },
          { id: 'FznfRjrPn3E', type: 'single_full', member: 'Seoyeon', anchor: 35.15 },
          { id: 'bNfIO_M0Djk', type: 'single_full', member: 'Chaeyoung', anchor: 35.09 },
          { id: '2SlQduAcJ6c', type: 'single_full', member: 'Nagyung', anchor: 35.07 },
          { id: 'Fu614M_0ns8', type: 'single_full', member: 'Jihun', anchor: 35.08 },
        ],
      },
      {
        id: 'f9_230618',
        title: 'Inkigayo',
        date: '2023. 6. 18.',
        anchor: 34,
        videos: [
          { id: 'MG1y6193q1w', type: 'main', anchor: 34.39 },
          { id: '1B0ecpXn0Vc', type: 'full', anchor: 33.91 },
          { id: '2WhEv4da0LI', type: 'single_face', member: 'Saerom', anchor: 54.64 },
          { id: 't5ZlGM5lcaY', type: 'single_face', member: 'Jiwon', anchor: 56.6 },
          { id: '_hNyFzZ2TPo', type: 'single_face', member: 'Jisun', anchor: 36.29 },
          { id: 'GGYyhIxPQ-o', type: 'single_face', member: 'Seoyeon', anchor: 46.07 },
          { id: 'lVtaM2ZsSWA', type: 'single_full', member: 'Nagyung', anchor: 33.13 },
          { id: 'T_ZoGeRCUBs', type: 'single_full', member: 'Jihun', anchor: 34.06 },
        ],
      },
    ],
  },
  {
    id: 'iam',
    title: 'I AM',
    group: 'IVE',
    album: IveIve,
    session: [
      {
        id: 'iv_230413',
        title: 'M COUNTDOWN',
        date: '2023. 4. 13.',
        anchor: 52,
        videos: [
          { id: 'dus7C4CTWUk', type: 'main', anchor: 61.64 },
          { id: 'FMZ5eA0a-VA', type: 'full', anchor: 103.8 },
          { id: 'EzB7hB8EaVU', type: 'single_full', member: 'Yujin', anchor: 54.47 },
          { id: 'g9AmSLZdVk8', type: 'single_face', member: 'Yujin', anchor: 52.06 },
          { id: 'JoYR_cQdsTQ', type: 'single_full', member: 'Gaeul', anchor: 54.44 },
          { id: '48yQAp5ra2w', type: 'single_face', member: 'Gaeul', anchor: 52.94 },
          { id: '9umB7Vp9bxY', type: 'single_full', member: 'Wonyoung', anchor: 54.43 },
          { id: 'cfRlXVNwV2E', type: 'single_face', member: 'Wonyoung', anchor: 95.2 },
          { id: 'PC0g2XTDZGc', type: 'single_full', member: 'Liz', anchor: 54.42 },
          { id: 'YgGPaTbUZCU', type: 'single_face', member: 'Liz', anchor: 54.69 },
          { id: '0izeq78RpHs', type: 'single_full', member: 'Leeseo', anchor: 54.42 },
          { id: 'WcxoyngF5wk', type: 'single_face', member: 'Leeseo', anchor: 53.13 },
        ],
      },
      {
        id: 'iv_230414',
        title: 'Music Bank',
        date: '2023. 4. 14.',
        anchor: 52,
        videos: [
          { id: 'el8QQFA3xKI', type: 'main', anchor: 59.88 },
          { id: 'BVf-pipXhN8', type: 'full', anchor: 51.8 },
          { id: 'o4uCQoG-2vE', type: '1take', anchor: 52.12 },
          { id: 'Jfm3z5IF9EY', type: 'single_full', member: 'Yujin', anchor: 52.09 },
          { id: 'pQXvySinRGU', type: 'single_face', member: 'Yujin', anchor: 52.32 },
          { id: '4A2wfok8U2E', type: 'single_full', member: 'Gaeul', anchor: 52.14 },
          { id: 'R-2_mKua8NA', type: 'single_face', member: 'Gaeul', anchor: 52.43 },
          { id: 'Ptdw-59QJ9k', type: 'single_full', member: 'Wonyoung', anchor: 52.1 },
          { id: 'LDNy2oJ22lM', type: 'single_face', member: 'Wonyoung', anchor: 51.76 },
          { id: 'BD4Ihmk2I2E', type: 'single_full', member: 'Liz', anchor: 52.22 },
          { id: 'a6hJf2iJ6jk', type: 'single_face', member: 'Liz', anchor: 52.45 },
          { id: '0If66frbJ78', type: 'single_full', member: 'Leeseo', anchor: 52.14 },
          { id: 'Ls1fhIiTxM4', type: 'single_face', member: 'Leeseo', anchor: 52.12 },
        ],
      },
      {
        id: 'iv_230415',
        title: 'Music Core',
        date: '2023. 4. 15.',
        anchor: 52,
        videos: [
          { id: 'XM78ZzK_dCM', type: 'main', anchor: 52.33 },
          { id: 'hXYaPEg8Pes', type: 'full', anchor: 53.1 },
          { id: '_TnFfJ_HCdI', type: 'single_full', member: 'Yujin', anchor: 53.97 },
          { id: '-LqZrSHRQ3E', type: 'single_face', member: 'Yujin', anchor: 52.57 },
          { id: 'vX66dsJBWlc', type: 'single_full', member: 'Gaeul', anchor: 52.21 },
          { id: 'eWOmgmR7kDs', type: 'single_face', member: 'Gaeul', anchor: 52.18 },
          { id: 'ZbfgiRfKE40', type: 'single_full', member: 'Wonyoung', anchor: 53.33 },
          { id: '06faE9OZ2ms', type: 'single_face', member: 'Wonyoung', anchor: 52.29 },
          { id: 'xzWtTxIgkyQ', type: 'single_full', member: 'Liz', anchor: 53.85 },
          { id: 'KjWRFTsf0bc', type: 'single_face', member: 'Liz', anchor: 52.09 },
          { id: 'XyLYx61AGsE', type: 'single_full', member: 'Leeseo', anchor: 52.82 },
          { id: 'eWeuPeJ1tY0', type: 'single_face', member: 'Leeseo', anchor: 52.89 },
        ],
      },
      {
        id: 'iv_230416',
        title: 'Inkigayo',
        date: '2023. 4. 16.',
        anchor: 52,
        videos: [
          { id: 'nnQddxQu2aU', type: 'main', anchor: 83.74 },
          { id: 'Z6SizsDLcrg', type: '1take', anchor: 52.16 },
          { id: 'SpLW2NcFsiY', type: 'tower', anchor: 52.54 },
          { id: 'zRHC7nYqxDk', type: 'full', anchor: 67.57 },
          { id: 'EtYWZzt3Iig', type: 'single_full', member: 'Yujin', anchor: 111.47 },
          { id: 'LKclCOjE1y4', type: 'single_face', member: 'Yujin', anchor: 81.42 },
          { id: '2ubER7dAra0', type: 'single_full', member: 'Gaeul', anchor: 73.8 },
          { id: 'COq08n8wl4k', type: 'single_face', member: 'Gaeul', anchor: 78.39 },
          { id: 'hzBt1AZcM2w', type: 'single_full', member: 'Wonyoung', anchor: 68.29 },
          { id: 'FBCR7eBuMNQ', type: 'single_face', member: 'Wonyoung', anchor: 67.64 },
          { id: 'yglwAIYeZnI', type: 'single_full', member: 'Liz', anchor: 70.62 },
          { id: '2n6eAHysdQU', type: 'single_face', member: 'Liz', anchor: 51.29 },
          { id: 'WqC8YK9ATqM', type: 'single_full', member: 'Leeseo', anchor: 92.01 },
          { id: 'iFo3dyxMjHY', type: 'single_face', member: 'Leeseo', anchor: 51.21 },
        ],
      },
      {
        id: 'iv_230420',
        title: 'M COUNTDOWN',
        date: '2023. 4. 20.',
        anchor: 52,
        videos: [
          { id: 'l4hf0JACcgU', type: 'main', anchor: 53.18 },
          { id: 'IjeDvs5PeYo', type: 'full', anchor: 52.24 },
          { id: 'KxCpYYwtQD4', type: 'single_full', member: 'Yujin', anchor: 51.25 },
          { id: 'kpKsvsAYJjA', type: 'single_face', member: 'Yujin', anchor: 52.06 },
          { id: 'gekN-tjcl4Y', type: 'single_full', member: 'Gaeul', anchor: 51.28 },
          { id: '8QBZn5-c6QQ', type: 'single_full', member: 'Wonyoung', anchor: 51.29 },
          { id: 'N9h8e8SHs_Q', type: 'single_face', member: 'Wonyoung', anchor: 51.91 },
          { id: '_7Lh3oMqdD4', type: 'single_full', member: 'Liz', anchor: 51.29 },
          { id: '0ZmrgdkP2nk', type: 'single_face', member: 'Liz', anchor: 52.49 },
          { id: 'uOBS2opNbwM', type: 'single_full', member: 'Leeseo', anchor: 51.33 },
        ],
      },
      {
        id: 'iv_230421',
        title: 'Music Bank',
        date: '2023. 4. 21.',
        anchor: 52,
        videos: [
          { id: '3s6l59R6jww', type: 'main', anchor: 65.72 },
          { id: 'GjoALzCN97s', type: 'full', anchor: 51.38 },
          { id: 'k_KuJoGjI4M', type: 'single_full', member: 'Yujin', anchor: 53.23 },
          { id: 'LzZeI__z47o', type: 'single_face', member: 'Yujin', anchor: 52.07 },
          { id: 'ULgmxEdT_w0', type: 'single_full', member: 'Gaeul', anchor: 53.29 },
          { id: 'oMkUcD3BH8c', type: 'single_full', member: 'Wonyoung', anchor: 53.24 },
          { id: 'Us9v3bJPK7Y', type: 'single_face', member: 'Wonyoung', anchor: 52.19 },
          { id: 'Z-CjQdbHcMo', type: 'single_full', member: 'Liz', anchor: 53.28 },
          { id: 'bDleRllukgM', type: 'single_full', member: 'Leeseo', anchor: 53.31 },
        ],
      },
      {
        id: 'iv_230422',
        title: 'Music Core',
        date: '2023. 4. 22.',
        anchor: 52,
        videos: [
          { id: 'vMXGX4Dp3iM', type: 'main', anchor: 52.54 },
          { id: 'UmQdkzFW02o', type: 'full', anchor: 52.38 },
          { id: 'hSKmLcdsjjQ', type: 'single_full', member: 'Yujin', anchor: 50.33 },
          { id: 'ocDBnUx3sK4', type: 'single_face', member: 'Yujin', anchor: 52.18 },
          { id: 'dKEqtJZgldM', type: 'single_full', member: 'Gaeul', anchor: 52.42 },
          { id: '-9hftESKRj0', type: 'single_face', member: 'Gaeul', anchor: 52.08 },
          { id: 'Ob5duBuI6I0', type: 'single_full', member: 'Wonyoung', anchor: 51.91 },
          { id: 'KEcWVoouaZU', type: 'single_face', member: 'Wonyoung', anchor: 52.2 },
          { id: 'dIPxPZNL4rc', type: 'single_full', member: 'Liz', anchor: 52.54 },
          { id: 'AqfR7lN6LMg', type: 'single_face', member: 'Liz', anchor: 52.13 },
          { id: 'cpvWYJEU9i0', type: 'single_full', member: 'Leeseo', anchor: 52.09 },
          { id: 'dqLuPzl5M7k', type: 'single_face', member: 'Leeseo', anchor: 54.26 },
        ],
      },
      {
        id: 'iv_230423',
        title: 'Inkigayo',
        date: '2023. 4. 23.',
        anchor: 52,
        videos: [
          { id: 'i6aSKcYwtMY', type: 'main', anchor: 54.19 },
          { id: 'O-4e_BCphSw', type: 'full', anchor: 52.08 },
          { id: 'n4_JPmceeNQ', type: 'single_full', member: 'Yujin', anchor: 53.69 },
          { id: 'CAqjHvMTFFw', type: 'single_full', member: 'Gaeul', anchor: 52.21 },
          { id: '-upaPSCKQeg', type: 'single_full', member: 'Wonyoung', anchor: 52.03 },
          { id: '45v7qN_aInI', type: 'single_face', member: 'Wonyoung', anchor: 52.06 },
          { id: 'Whsq-NxScdc', type: 'single_full', member: 'Liz', anchor: 52 },
          { id: 'vXCjn3u54b4', type: 'single_face', member: 'Liz', anchor: 51.96 },
          { id: 'J-TsdSiOn8Y', type: 'single_full', member: 'Leeseo', anchor: 52.07 },
          { id: '6gK9nQ2OGIA', type: 'single_face', member: 'Leeseo', anchor: 51.93 },
        ],
      },
    ],
  },
];

export default IXVXStore;
