import BloomIz from '@/public/album/bloom_iz.png';
import UnlockMyWorld from '@/public/album/unlock_my_world.png';
import IveIve from '@/public/album/ive_ive.png';
import Expergo from '@/public/album/expergo.png';
import MyWorld from '@/public/album/my_world.png';
import Unforgiven from '@/public/album/unforgiven.png';
import Omg from '@/public/album/omg.png';
import TeddyBear from '@/public/album/teddy_bear.png';

const IXVXStore: Music[] = [
  {
    id: 'fiesta',
    title: 'FIESTA',
    group: 'IZ*ONE',
    album: Unforgiven,
    anchor: 48.3,
    session: [
      {
        id: 'iz_200217',
        title: 'COMEBACK IZ*ONE BLOOM*IZ',
        date: '2020. 2. 17.',
        videos: [
          { id: 'mbdArlIBPHk', type: 'main', anchor: 47.58 },
          { id: 'XEhwvuOBlCA', type: 'full', anchor: 47.8 },
          { id: 'XoHmQ7cL1gI', type: 'single_full', member: 'Eunbi', anchor: 47.78 },
          { id: 'vpQdW_3Wfac', type: 'single_full', member: 'Sakura', anchor: 47.74 },
          { id: 'uLy-ze05z2E', type: 'single_face', member: 'Sakura', anchor: 47.71 },
          { id: 'cwUB3AH4vbY', type: 'single_full', member: 'Hyewon', anchor: 47.73 },
          { id: '5bM7mt0d6t8', type: 'single_full', member: 'Yena', anchor: 47.74 },
          { id: 'EnZG4op_8dA', type: 'single_full', member: 'Chaeyeon', anchor: 47.72 },
          { id: 'CQ5XPxPoJQA', type: 'single_full', member: 'Chaewon', anchor: 47.75 },
          { id: 'e0REO_PUZ54', type: 'single_face', member: 'Chaewon', anchor: 47.76 },
          { id: 'RsbWx_I-hv8', type: 'single_full', member: 'Minju', anchor: 47.7 },
          { id: '5JcdG5EbgYw', type: 'single_face', member: 'Minju', anchor: 47.74 },
          { id: 'r2ZxOSbR0M4', type: 'single_full', member: 'Nako', anchor: 47.68 },
          { id: 'BFa-2McO_to', type: 'single_full', member: 'Hitomi', anchor: 47.74 },
          { id: 'LBh3P4I8wX8', type: 'single_full', member: 'Yuri', anchor: 47.73 },
          { id: '6AL7WUYYUsY', type: 'single_full', member: 'Yujin', anchor: 47.72 },
          { id: 'V5TppOVxpbo', type: 'single_full', member: 'Wonyoung', anchor: 47.74 },
          { id: 'zPAUb9V6owM', type: 'single_face', member: 'Wonyoung', anchor: 47.76 },
        ],
      },
      {
        id: 'iz_200220',
        title: 'M COUNTDOWN',
        date: '2020. 2. 20.',
        videos: [
          { id: 'AK0CWZ5_kGk', type: 'main', anchor: 62.18 },
          { id: 'hC_yoargvOU', type: 'full', anchor: 46.85 },
          { id: 'iYGfPhrGNpg', type: 'single_full', member: 'Eunbi', anchor: 46.84 },
          { id: 'UETG8syaOW4', type: 'single_full', member: 'Sakura', anchor: 46.86 },
          { id: 'II6wIQ_w29Y', type: 'single_full', member: 'Hyewon', anchor: 46.83 },
          { id: '9CwW-OjSBWo', type: 'single_full', member: 'Yena', anchor: 46.84 },
          { id: 'MOdf_kVTZTQ', type: 'single_full', member: 'Chaeyeon', anchor: 46.83 },
          { id: 'gHeNTYEl6Jo', type: 'single_full', member: 'Chaewon', anchor: 46.82 },
          { id: 'cceQl_u4FcE', type: 'single_full', member: 'Minju', anchor: 46.82 },
          { id: 'YdSn6l3d8KY', type: 'single_full', member: 'Nako', anchor: 46.83 },
          { id: 'mJ1580KZeAg', type: 'single_face', member: 'Nako', anchor: 46.89 },
          { id: '8S2AND-lZXA', type: 'single_full', member: 'Hitomi', anchor: 46.86 },
          { id: 'm7ReW0Ag_Gg', type: 'single_full', member: 'Yuri', anchor: 46.82 },
          { id: 'sg8RonUPWmM', type: 'single_face', member: 'Yuri', anchor: 47.47 },
          { id: 'W9sFLa9yzME', type: 'single_full', member: 'Yujin', anchor: 46.85 },
          { id: 'q9lI7haUPCc', type: 'single_full', member: 'Wonyoung', anchor: 46.88 },
        ],
      },
      {
        id: 'iz_200221',
        title: 'Music Bank',
        date: '2020. 2. 21.',
        videos: [
          { id: 'BL0O0twDoCY', type: 'main', anchor: 49.36 },
          { id: 'qNCEIGCb3yM', type: 'full', anchor: 47.32 },
          { id: 't2Jh4uY3K2w', type: 'single_full', member: 'Sakura', anchor: 47.38 },
          { id: '6R2PXqEt91M', type: 'single_full', member: 'Wonyoung', anchor: 47.37 },
        ],
      },
      {
        id: 'iz_200223',
        title: 'Inkigayo',
        date: '2020. 2. 23.',
        videos: [
          { id: 'yN7TEJcMs_A', type: 'main', anchor: 47.26 },
          { id: 'vw3iFRxO0ZE', type: 'full', anchor: 47.41 },
          { id: '7uKgDG_WaEs', type: '1take', anchor: 48.3 },
          { id: 'jVVl-rVG4Gg', type: 'tower', anchor: 49.49 },
          { id: '_FaaybcEPbQ', type: 'single_full', member: 'Sakura', anchor: 49.4 },
          { id: 'yr2q0xeoUsw', type: 'single_full', member: 'Hyewon', anchor: 47.49 },
          { id: '_dBEvXKdUu8', type: 'single_full', member: 'Yena', anchor: 48.5 },
          { id: 'O5md6nf9qTY', type: 'single_face', member: 'Yena', anchor: 47.9 },
          { id: 'KrJ1YXhW-kE', type: 'single_full', member: 'Chaeyeon', anchor: 48.08 },
          { id: '9wVQ2GPQ_kI', type: 'single_full', member: 'Chaewon', anchor: 48.52 },
          { id: '2dAQnk74TqM', type: 'single_face', member: 'Chaewon', anchor: 47.73 },
          { id: 'ORnANdGwjp8', type: 'single_full', member: 'Minju', anchor: 49.31 },
          { id: 'xo5At3B8GfE', type: 'single_full', member: 'Nako', anchor: 47.86 },
          { id: 'x1NMfKIPfSU', type: 'single_full', member: 'Hitomi', anchor: 47.68 },
          { id: '3gA6hb9Wwh8', type: 'single_face', member: 'Hitomi', anchor: 47.39 },
          { id: 'j8L2uLFhYu8', type: 'single_full', member: 'Yuri', anchor: 48.21 },
          { id: 'Efs6UDZxkgE', type: 'single_full', member: 'Yujin', anchor: 47.84 },
          { id: 'AmidiHNuBQs', type: 'single_full', member: 'Wonyoung', anchor: 47.46 },
          { id: 'kLDgaEs99_s', type: 'single_face', member: 'Wonyoung', anchor: 54.16 },
        ],
      },
      {
        id: 'iz_200225',
        title: 'THE SHOW',
        date: '2020. 2. 25.',
        videos: [
          { id: 'UaU1YKVFOJM', type: 'main', anchor: 59.48 },
          { id: 'C7FHQc3tUbI', type: 'full', anchor: 47.73 },
          { id: 'dRjPhhjJHo4', type: 'live', anchor: 124.78 },
        ],
      },
      {
        id: 'iz_200226',
        title: 'Show Champion',
        date: '2020. 2. 26.',
        videos: [
          { id: 'Tij0p1FQDOk', type: 'main', anchor: 59.2 },
          { id: '7Nj-hf-L6ug', type: 'full', anchor: 48.28 },
          { id: 'NAvSwDBqPWo', type: 'single_full', member: 'Sakura', anchor: 48.29 },
          { id: 'qQePmU3f9EE', type: 'single_full', member: 'Chaeyeon', anchor: 48.3 },
          { id: 'xP524_LnY4s', type: 'single_full', member: 'Chaewon', anchor: 48.29 },
          { id: 'rJTLD-gGSmc', type: 'single_full', member: 'Yuri', anchor: 48.29 },
          { id: 'zSDs7bnCQag', type: 'single_full', member: 'Yujin', anchor: 48.29 },
          { id: 'PCZ3t-aFDDA', type: 'single_full', member: 'Wonyoung', anchor: 48.34 },
        ],
      },
      {
        id: 'iz_200227',
        title: 'M COUNTDOWN',
        date: '2020. 2. 27.',
        videos: [
          { id: '6t2dP3qyZs8', type: 'main', anchor: 47.97 },
          { id: 'zwHfn2ULgIA', type: 'full', anchor: 46.75 },
          { id: 'Zgowsl45oDI', type: 'live', anchor: 111.95 },
          { id: 'vvwR1KinlHE', type: 'single_full', member: 'Sakura', anchor: 46.83 },
          { id: '7wiBpstsS3I', type: 'single_full', member: 'Chaeyeon', anchor: 46.73 },
          { id: 'GKI48FZx-zM', type: 'single_full', member: 'Minju', anchor: 46.79 },
        ],
      },
      {
        id: 'iz_200301',
        title: 'Inkigayo',
        date: '2020. 3. 1.',
        videos: [
          { id: 'BprWpSsaI_U', type: 'main', anchor: 47.42 },
          { id: '0z-WHyT_tXU', type: 'full', anchor: 47.7 },
          { id: 'wyuPG4JDKB4', type: '1take', anchor: 47.44 },
          { id: 'LZVZNPiX8C8', type: 'tower', anchor: 47.48 },
          { id: 't9zhDs2Yomo', type: 'side', anchor: 48.29 },
          { id: 'LxZoH7VIuOQ', type: 'single_full', member: 'Eunbi', anchor: 47.71 },
          { id: 'cCObI-CEiHY', type: 'single_face', member: 'Eunbi', anchor: 47.45 },
          { id: 'fZ4reyA5PS8', type: 'single_face', member: 'Sakura', anchor: 49.86 },
          { id: 'jjw_O8rThCQ', type: 'single_face', member: 'Hyewon', anchor: 47.58 },
          { id: 'ARWGlJc-C6E', type: 'single_face', member: 'Yena', anchor: 47.38 },
          { id: 'lsSKxjZkgLk', type: 'single_full', member: 'Chaeyeon', anchor: 47.66 },
          { id: '2YYuPOzsaiI', type: 'single_face', member: 'Chaeyeon', anchor: 83.15 },
          { id: '9x_J4P2IWso', type: 'single_face', member: 'Chaewon', anchor: 47.47 },
          { id: 'TllUZp2Ku64', type: 'single_face', member: 'Nako', anchor: 56.63 },
          { id: 'q7CNl4Sqh2g', type: 'single_face', member: 'Hitomi', anchor: 48.63 },
          { id: 'RALtJirAA-o', type: 'single_face', member: 'Yuri', anchor: 48.11 },
          { id: 'hZkeX-o4JaU', type: 'single_face', member: 'Yujin', anchor: 47.47 },
          { id: 'n6_IDfYqP0A', type: 'single_full', member: 'Wonyoung', anchor: 47.72 },
          { id: 'A7DuELiqhIU', type: 'single_face', member: 'Wonyoung', anchor: 54.57 },
        ],
      },
      {
        id: 'iz_200303',
        title: 'THE SHOW',
        date: '2020. 3. 3.',
        videos: [
          { id: 'NxuQ1A6ppVQ', type: 'main', anchor: 47.53 },
          { id: '4nPG54QFP1U', type: 'full', anchor: 47.67 },
          { id: 'JLu0bmk2Brk', type: 'live', anchor: 116.61 },
        ],
      },
      {
        id: 'iz_200304',
        title: 'Show Champion',
        date: '2020. 3. 4.',
        videos: [
          { id: 'a0T1UnYxtus', type: 'main', anchor: 47.77 },
          { id: 'rS9i2RmNrec', type: 'full', anchor: 48.14 },
          { id: 'GD8uc0b_uDw', type: 'single_full', member: 'Eunbi', anchor: 48.34 },
          { id: 'ugsOn3T5RDs', type: 'single_full', member: 'Sakura', anchor: 48.11 },
          { id: 'K7c3oqttP2k', type: 'single_full', member: 'Yena', anchor: 48.13 },
          { id: 'VTFK3WydnvM', type: 'single_full', member: 'Chaewon', anchor: 48.14 },
          { id: 'O_N15tYHXT0', type: 'single_full', member: 'Minju', anchor: 48.13 },
          { id: 'CtsmINWkk6k', type: 'single_full', member: 'Wonyoung', anchor: 48.19 },
        ],
      },
      {
        id: 'iz_200305',
        title: 'M COUNTDOWN',
        date: '2020. 3. 5.',
        videos: [
          { id: 'xpmr2I77PNU', type: 'main', anchor: 47.46 },
          { id: 'ELU_YLPDCY8', type: 'full', anchor: 47.08 },
          { id: 'voHIbMnc3vg', type: 'single_full', member: 'Eunbi', anchor: 47.02 },
          { id: 'Ky2Ui5zJoVk', type: 'single_face', member: 'Hyewon', anchor: 47.4 },
          { id: 'AJGWwHcFY0E', type: 'single_face', member: 'Chaeyeon', anchor: 47.47 },
          { id: 'Nr9PdYgkmto', type: 'single_face', member: 'Hitomi', anchor: 47.35 },
          { id: 'EzjTl2Oyx-A', type: 'single_full', member: 'Yuri', anchor: 47.1 },
          { id: 'VkRZCJXhMZQ', type: 'single_full', member: 'Wonyoung', anchor: 47.06 },
        ],
      },
      {
        id: 'iz_200307',
        title: 'Music Core',
        date: '2020. 3. 7.',
        videos: [
          { id: 'YcLdFzOmjyU', type: 'main', anchor: 46.03 },
          { id: 'FLUcocSIxCk', type: 'full', anchor: 47.38 },
          { id: 'yR9d4HLyebU', type: 'single_full', member: 'Sakura', anchor: 47.3 },
          { id: 'z1jAhj8PGys', type: 'single_full', member: 'Chaeyeon', anchor: 47.26 },
          { id: 'uGn8xmxzutg', type: 'single_full', member: 'Chaewon', anchor: 47.46 },
          { id: 'u6vRITvDjJU', type: 'single_full', member: 'Yuri', anchor: 47.35 },
          { id: 'TX9xFuNH8pQ', type: 'single_full', member: 'Wonyoung', anchor: 47.33 },
        ],
      },
      {
        id: 'iz_200308',
        title: 'Inkigayo',
        date: '2020. 3. 8.',
        videos: [
          { id: 'G37U12n-Wqs', type: 'main', anchor: 47.85 },
          { id: 'g-CANwH3i4o', type: 'full', anchor: 47.42 },
          { id: 'eVtospUsf8c', type: 'single_face', member: 'Eunbi', anchor: 47.44 },
          { id: 'hp6uq7N-_cc', type: 'single_face', member: 'Sakura', anchor: 47.61 },
          { id: 'tpTbp099t-E', type: 'single_face', member: 'Yena', anchor: 48.07 },
          { id: 'k_vYMbe7fcw', type: 'single_full', member: 'Chaeyeon', anchor: 50.08 },
          { id: '9gZIUHRD7XA', type: 'single_face', member: 'Chaeyeon', anchor: 67.84 },
          { id: 'jEmrvBI6xC8', type: 'single_face', member: 'Chaewon', anchor: 47.94 },
          { id: '_xW9mXkGu5w', type: 'single_face', member: 'Nako', anchor: 48.24 },
          { id: 'ZOAU9l1Ba7Y', type: 'single_full', member: 'Hitomi', anchor: 51.04 },
          { id: 'FTzk6wdiFTo', type: 'single_face', member: 'Wonyoung', anchor: 47.66 },
        ],
      },
    ],
  },
  {
    id: 'menow',
    title: '#menow',
    group: 'fromis_9',
    album: UnlockMyWorld,
    anchor: 34.47,
    session: [
      {
        id: 'f9_230608',
        title: 'M COUNTDOWN',
        date: '2023. 06. 08.',
        videos: [
          { id: '12wE8piFkfo', type: 'main', anchor: 42.65 },
          { id: 'LZVVV0UkWHE', type: 'full', anchor: 37.07 },
          { id: 'pN4FKoKH1UY', type: 'single_full', member: 'Hayoung', anchor: 34.1 },
          { id: 'jryio89EE2k', type: 'single_full', member: 'Jisun', anchor: 34.17 },
          { id: '1iB4VufTZTo', type: 'single_full', member: 'Chaeyoung', anchor: 34.1 },
          { id: 'qygwNJjXODI', type: 'single_face', member: 'Nagyung', anchor: 35.95 },
          { id: 'ItQ_cE1nZ1Y', type: 'single_full', member: 'Nagyung', anchor: 34.14 },
          { id: 'Ldtx1Fq2XTw', type: 'single_face', member: 'Jihun', anchor: 36.1 },
          { id: 'uL5-y3NB9Gk', type: 'single_full', member: 'Jihun', anchor: 34.17 },
        ],
      },
      {
        id: 'f9_230609',
        title: 'Music Bank',
        date: '2023. 06. 09.',
        videos: [
          { id: 'ygU0M8AoeAg', type: 'main', anchor: 40.78 },
          { id: 'Vf11ARSBYCw', type: 'full', anchor: 34.43 },
          { id: 'WUN6cjDXxnY', type: 'single_full', member: 'Saerom', anchor: 34.55 },
          { id: 'KGiIvjibTmQ', type: 'single_face', member: 'Hayoung', anchor: 41.59 },
          { id: 'pc3J0o_L0HY', type: 'single_full', member: 'Hayoung', anchor: 34.51 },
          { id: 'JVdorps9JuQ', type: 'single_full', member: 'Jiwon', anchor: 34.52 },
          { id: 'tkraDAyhiPg', type: 'single_full', member: 'Jisun', anchor: 34.49 },
          { id: '-7VgOH50Zm4', type: 'single_full', member: 'Seoyeon', anchor: 34.44 },
          { id: '4-elCfjQLp8', type: 'single_face', member: 'Chaeyoung', anchor: 34.2 },
          { id: '_58y-7QmHvw', type: 'single_full', member: 'Chaeyoung', anchor: 34.41 },
          { id: 'fnjyQzSja7o', type: 'single_face', member: 'Nagyung', anchor: 34.18 },
          { id: 'bQ2916lrN34', type: 'single_full', member: 'Nagyung', anchor: 34.58 },
          { id: 'SxuZJ9vPf9I', type: 'single_face', member: 'Jihun', anchor: 35.11 },
          { id: 'W3spS56XzQg', type: 'single_full', member: 'Jihun', anchor: 34.53 },
        ],
      },
      {
        id: 'f9_230611',
        title: 'Inkigayo',
        date: '2023. 6. 11.',
        videos: [
          { id: 'fKaA7QNA8KM', type: 'main', anchor: 39.25 },
          { id: 'rh8QX9EGjwM', type: 'full', anchor: 42.76 },
          { id: 'llyuudJMJRI', type: '1take', anchor: 34.72 },
          { id: 'WHaxN0KHls8', type: 'single_full', member: 'Saerom', anchor: 38.35 },
          { id: 'cCKJ0yNW4Yg', type: 'single_full', member: 'Hayoung', anchor: 51.92 },
          { id: 'pJ4S4OpT4uw', type: 'single_face', member: 'Hayoung', anchor: 34.22 },
          { id: 'xeBR1dPtxXM', type: 'single_full', member: 'Jiwon', anchor: 41.2 },
          { id: '48BfU5nLchw', type: 'single_full', member: 'Jisun', anchor: 34.18 },
          { id: 'uCdqgYBjuFg', type: 'single_full', member: 'Seoyeon', anchor: 40.49 },
          { id: 'j97OscmKOmI', type: 'single_full', member: 'Chaeyoung', anchor: 34.2 },
          { id: '2ghWS9moAQg', type: 'single_face', member: 'Chaeyoung', anchor: 36.76 },
          { id: '3aSqJza7CJg', type: 'single_full', member: 'Nagyung', anchor: 45.13 },
          { id: 'I0yLI_QYmj0', type: 'single_face', member: 'Nagyung', anchor: 48.94 },
          { id: 'qffpeTS4bJA', type: 'single_full', member: 'Jihun', anchor: 49.47 },
          { id: '5OBwkVpnNFM', type: 'single_face', member: 'Jihun', anchor: 42.67 },
        ],
      },
      {
        id: 'f9_230614',
        title: 'Show Champion',
        date: '2023. 6. 14.',
        videos: [
          { id: 'oqtLzpv9MDM', type: 'main', anchor: 45.52 },
          { id: 'Zr6w0m9hKeE', type: 'full', anchor: 35.09 },
          { id: 'IUtN6X7tEhg', type: 'single_full', member: 'Saerom', anchor: 35.1 },
          { id: 'DMMeBBvrQKo', type: 'single_full', member: 'Hayoung', anchor: 35.08 },
          { id: 'holBjxVWReU', type: 'single_full', member: 'Jiwon', anchor: 35.08 },
          { id: 'vwRcJViIBcw', type: 'single_full', member: 'Jisun', anchor: 35.08 },
          { id: 'FznfRjrPn3E', type: 'single_full', member: 'Seoyeon', anchor: 35.15 },
          { id: 'bNfIO_M0Djk', type: 'single_full', member: 'Chaeyoung', anchor: 35.09 },
          { id: '2SlQduAcJ6c', type: 'single_full', member: 'Nagyung', anchor: 35.07 },
          { id: 'Fu614M_0ns8', type: 'single_full', member: 'Jihun', anchor: 35.08 },
        ],
      },
      {
        id: 'f9_230618',
        title: 'Inkigayo',
        date: '2023. 6. 18.',
        videos: [
          { id: 'MG1y6193q1w', type: 'main', anchor: 34.39 },
          { id: '1B0ecpXn0Vc', type: 'full', anchor: 33.91 },
          { id: '2WhEv4da0LI', type: 'single_face', member: 'Saerom', anchor: 54.64 },
          { id: 't5ZlGM5lcaY', type: 'single_face', member: 'Jiwon', anchor: 56.6 },
          { id: '_hNyFzZ2TPo', type: 'single_face', member: 'Jisun', anchor: 36.29 },
          { id: 'GGYyhIxPQ-o', type: 'single_face', member: 'Seoyeon', anchor: 46.07 },
          { id: 'lVtaM2ZsSWA', type: 'single_full', member: 'Nagyung', anchor: 33.13 },
          { id: 'T_ZoGeRCUBs', type: 'single_full', member: 'Jihun', anchor: 34.06 },
        ],
      },
    ],
  },
  {
    id: 'iam',
    title: 'I AM',
    group: 'IVE',
    album: IveIve,
    anchor: 52.61,
    session: [
      {
        id: 'iv_230413',
        title: 'M COUNTDOWN',
        date: '2023. 4. 13.',
        videos: [
          { id: 'dus7C4CTWUk', type: 'main', anchor: 61.64 },
          { id: 'FMZ5eA0a-VA', type: 'full', anchor: 103.8 },
          { id: 'EzB7hB8EaVU', type: 'single_full', member: 'Yujin', anchor: 54.47 },
          { id: 'g9AmSLZdVk8', type: 'single_face', member: 'Yujin', anchor: 52.06 },
          { id: 'JoYR_cQdsTQ', type: 'single_full', member: 'Gaeul', anchor: 54.44 },
          { id: '48yQAp5ra2w', type: 'single_face', member: 'Gaeul', anchor: 52.94 },
          { id: '9umB7Vp9bxY', type: 'single_full', member: 'Wonyoung', anchor: 54.43 },
          { id: 'cfRlXVNwV2E', type: 'single_face', member: 'Wonyoung', anchor: 95.2 },
          { id: 'PC0g2XTDZGc', type: 'single_full', member: 'Liz', anchor: 54.42 },
          { id: 'YgGPaTbUZCU', type: 'single_face', member: 'Liz', anchor: 54.69 },
          { id: '0izeq78RpHs', type: 'single_full', member: 'Leeseo', anchor: 54.42 },
          { id: 'WcxoyngF5wk', type: 'single_face', member: 'Leeseo', anchor: 53.13 },
        ],
      },
      {
        id: 'iv_230414',
        title: 'Music Bank',
        date: '2023. 4. 14.',
        videos: [
          { id: 'el8QQFA3xKI', type: 'main', anchor: 59.88 },
          { id: 'BVf-pipXhN8', type: 'full', anchor: 51.8 },
          { id: 'o4uCQoG-2vE', type: '1take', anchor: 52.12 },
          { id: 'Jfm3z5IF9EY', type: 'single_full', member: 'Yujin', anchor: 52.09 },
          { id: 'pQXvySinRGU', type: 'single_face', member: 'Yujin', anchor: 52.32 },
          { id: '4A2wfok8U2E', type: 'single_full', member: 'Gaeul', anchor: 52.14 },
          { id: 'R-2_mKua8NA', type: 'single_face', member: 'Gaeul', anchor: 52.43 },
          { id: 'Ptdw-59QJ9k', type: 'single_full', member: 'Wonyoung', anchor: 52.1 },
          { id: 'LDNy2oJ22lM', type: 'single_face', member: 'Wonyoung', anchor: 51.76 },
          { id: 'BD4Ihmk2I2E', type: 'single_full', member: 'Liz', anchor: 52.22 },
          { id: 'a6hJf2iJ6jk', type: 'single_face', member: 'Liz', anchor: 52.45 },
          { id: '0If66frbJ78', type: 'single_full', member: 'Leeseo', anchor: 52.14 },
          { id: 'Ls1fhIiTxM4', type: 'single_face', member: 'Leeseo', anchor: 52.12 },
        ],
      },
      {
        id: 'iv_230415',
        title: 'Music Core',
        date: '2023. 4. 15.',
        videos: [
          { id: 'XM78ZzK_dCM', type: 'main', anchor: 52.33 },
          { id: 'hXYaPEg8Pes', type: 'full', anchor: 53.1 },
          { id: '_TnFfJ_HCdI', type: 'single_full', member: 'Yujin', anchor: 53.97 },
          { id: '-LqZrSHRQ3E', type: 'single_face', member: 'Yujin', anchor: 52.57 },
          { id: 'vX66dsJBWlc', type: 'single_full', member: 'Gaeul', anchor: 52.21 },
          { id: 'eWOmgmR7kDs', type: 'single_face', member: 'Gaeul', anchor: 52.18 },
          { id: 'ZbfgiRfKE40', type: 'single_full', member: 'Wonyoung', anchor: 53.33 },
          { id: '06faE9OZ2ms', type: 'single_face', member: 'Wonyoung', anchor: 52.29 },
          { id: 'xzWtTxIgkyQ', type: 'single_full', member: 'Liz', anchor: 53.85 },
          { id: 'KjWRFTsf0bc', type: 'single_face', member: 'Liz', anchor: 52.09 },
          { id: 'XyLYx61AGsE', type: 'single_full', member: 'Leeseo', anchor: 52.82 },
          { id: 'eWeuPeJ1tY0', type: 'single_face', member: 'Leeseo', anchor: 52.89 },
        ],
      },
      {
        id: 'iv_230416',
        title: 'Inkigayo',
        date: '2023. 4. 16.',
        videos: [
          { id: 'nnQddxQu2aU', type: 'main', anchor: 83.74 },
          { id: 'Z6SizsDLcrg', type: '1take', anchor: 52.16 },
          { id: 'SpLW2NcFsiY', type: 'tower', anchor: 52.54 },
          { id: 'zRHC7nYqxDk', type: 'full', anchor: 67.57 },
          { id: 'EtYWZzt3Iig', type: 'single_full', member: 'Yujin', anchor: 111.47 },
          { id: 'LKclCOjE1y4', type: 'single_face', member: 'Yujin', anchor: 81.42 },
          { id: '2ubER7dAra0', type: 'single_full', member: 'Gaeul', anchor: 73.8 },
          { id: 'COq08n8wl4k', type: 'single_face', member: 'Gaeul', anchor: 78.39 },
          { id: 'hzBt1AZcM2w', type: 'single_full', member: 'Wonyoung', anchor: 68.29 },
          { id: 'FBCR7eBuMNQ', type: 'single_face', member: 'Wonyoung', anchor: 67.64 },
          { id: 'yglwAIYeZnI', type: 'single_full', member: 'Liz', anchor: 70.62 },
          { id: '2n6eAHysdQU', type: 'single_face', member: 'Liz', anchor: 51.29 },
          { id: 'WqC8YK9ATqM', type: 'single_full', member: 'Leeseo', anchor: 92.01 },
          { id: 'iFo3dyxMjHY', type: 'single_face', member: 'Leeseo', anchor: 51.21 },
        ],
      },
      {
        id: 'iv_230420',
        title: 'M COUNTDOWN',
        date: '2023. 4. 20.',
        videos: [
          { id: 'l4hf0JACcgU', type: 'main', anchor: 53.18 },
          { id: 'IjeDvs5PeYo', type: 'full', anchor: 52.24 },
          { id: 'KxCpYYwtQD4', type: 'single_full', member: 'Yujin', anchor: 51.25 },
          { id: 'kpKsvsAYJjA', type: 'single_face', member: 'Yujin', anchor: 52.06 },
          { id: 'gekN-tjcl4Y', type: 'single_full', member: 'Gaeul', anchor: 51.28 },
          { id: '8QBZn5-c6QQ', type: 'single_full', member: 'Wonyoung', anchor: 51.29 },
          { id: 'N9h8e8SHs_Q', type: 'single_face', member: 'Wonyoung', anchor: 51.91 },
          { id: '_7Lh3oMqdD4', type: 'single_full', member: 'Liz', anchor: 51.29 },
          { id: '0ZmrgdkP2nk', type: 'single_face', member: 'Liz', anchor: 52.49 },
          { id: 'uOBS2opNbwM', type: 'single_full', member: 'Leeseo', anchor: 51.33 },
        ],
      },
      {
        id: 'iv_230421',
        title: 'Music Bank',
        date: '2023. 4. 21.',
        videos: [
          { id: '3s6l59R6jww', type: 'main', anchor: 65.72 },
          { id: 'GjoALzCN97s', type: 'full', anchor: 51.38 },
          { id: 'k_KuJoGjI4M', type: 'single_full', member: 'Yujin', anchor: 53.23 },
          { id: 'LzZeI__z47o', type: 'single_face', member: 'Yujin', anchor: 52.07 },
          { id: 'ULgmxEdT_w0', type: 'single_full', member: 'Gaeul', anchor: 53.29 },
          { id: 'oMkUcD3BH8c', type: 'single_full', member: 'Wonyoung', anchor: 53.24 },
          { id: 'Us9v3bJPK7Y', type: 'single_face', member: 'Wonyoung', anchor: 52.19 },
          { id: 'Z-CjQdbHcMo', type: 'single_full', member: 'Liz', anchor: 53.28 },
          { id: 'bDleRllukgM', type: 'single_full', member: 'Leeseo', anchor: 53.31 },
        ],
      },
      {
        id: 'iv_230422',
        title: 'Music Core',
        date: '2023. 4. 22.',
        videos: [
          { id: 'vMXGX4Dp3iM', type: 'main', anchor: 52.54 },
          { id: 'UmQdkzFW02o', type: 'full', anchor: 52.38 },
          { id: 'hSKmLcdsjjQ', type: 'single_full', member: 'Yujin', anchor: 50.33 },
          { id: 'ocDBnUx3sK4', type: 'single_face', member: 'Yujin', anchor: 52.18 },
          { id: 'dKEqtJZgldM', type: 'single_full', member: 'Gaeul', anchor: 52.42 },
          { id: '-9hftESKRj0', type: 'single_face', member: 'Gaeul', anchor: 52.08 },
          { id: 'Ob5duBuI6I0', type: 'single_full', member: 'Wonyoung', anchor: 51.91 },
          { id: 'KEcWVoouaZU', type: 'single_face', member: 'Wonyoung', anchor: 52.2 },
          { id: 'dIPxPZNL4rc', type: 'single_full', member: 'Liz', anchor: 52.54 },
          { id: 'AqfR7lN6LMg', type: 'single_face', member: 'Liz', anchor: 52.13 },
          { id: 'cpvWYJEU9i0', type: 'single_full', member: 'Leeseo', anchor: 52.09 },
          { id: 'dqLuPzl5M7k', type: 'single_face', member: 'Leeseo', anchor: 54.26 },
        ],
      },
      {
        id: 'iv_230423',
        title: 'Inkigayo',
        date: '2023. 4. 23.',
        videos: [
          { id: 'i6aSKcYwtMY', type: 'main', anchor: 54.19 },
          { id: 'O-4e_BCphSw', type: 'full', anchor: 52.08 },
          { id: 'n4_JPmceeNQ', type: 'single_full', member: 'Yujin', anchor: 53.69 },
          { id: 'CAqjHvMTFFw', type: 'single_full', member: 'Gaeul', anchor: 52.21 },
          { id: '-upaPSCKQeg', type: 'single_full', member: 'Wonyoung', anchor: 52.03 },
          { id: '45v7qN_aInI', type: 'single_face', member: 'Wonyoung', anchor: 52.06 },
          { id: 'Whsq-NxScdc', type: 'single_full', member: 'Liz', anchor: 52 },
          { id: 'vXCjn3u54b4', type: 'single_face', member: 'Liz', anchor: 51.96 },
          { id: 'J-TsdSiOn8Y', type: 'single_full', member: 'Leeseo', anchor: 52.07 },
          { id: '6gK9nQ2OGIA', type: 'single_face', member: 'Leeseo', anchor: 51.93 },
        ],
      },
    ],
  },
  {
    id: 'kitsch',
    title: 'Kitsch',
    group: 'IVE',
    album: IveIve,
    anchor: 5.39,
    session: [
      {
        id: 'iv_230413',
        title: 'M COUNTDOWN',
        date: '2023. 4. 13.',
        videos: [
          { id: 'S4XzqoeGQnA', type: 'main', anchor: 14.47 },
          { id: 'vmbXpnFRJ6s', type: 'full', anchor: 14.51 },
          { id: 'kYdWmnu4Qdo', type: 'single_full', member: 'Yujin', anchor: 6.22 },
          { id: '9hhYHk7GVpI', type: 'single_face', member: 'Yujin', anchor: 4.76 },
          { id: 'O6XSmVCFiuY', type: 'single_full', member: 'Gaeul', anchor: 6.21 },
          { id: 'TKAeRB4k20Y', type: 'single_face', member: 'Gaeul', anchor: 16.47 },
          { id: 'dJ9EFmcudpg', type: 'single_full', member: 'Wonyoung', anchor: 6.21 },
          { id: 'd63nIGX00YM', type: 'single_face', member: 'Wonyoung', anchor: 5.5 },
          { id: '1EnVhVTxd1s', type: 'single_full', member: 'Liz', anchor: 6.17 },
          { id: 'MxcZL6wixwg', type: 'single_full', member: 'Leeseo', anchor: 6.16 },
          { id: 'phmfOEjBo9k', type: 'single_face', member: 'Leeseo', anchor: 16.45 },
        ],
      },
      {
        id: 'iv_230414',
        title: 'Music Bank',
        date: '2023. 4. 14.',
        videos: [
          { id: 'LOnBNa7B8iQ', type: 'main', anchor: 15.09 },
          { id: 'UibLePSMnRw', type: 'full', anchor: 5.4 },
          { id: 'DxwZW-h5OdQ', type: 'single_full', member: 'Yujin', anchor: 5.41 },
          { id: 'A7eDNlAWHZk', type: 'single_face', member: 'Yujin', anchor: 6.01 },
          { id: '5zkhNvhATiI', type: 'single_full', member: 'Gaeul', anchor: 5.36 },
          { id: 'moSP7unB7l8', type: 'single_face', member: 'Gaeul', anchor: 5.04 },
          { id: 'tj92CbaqQo4', type: 'single_full', member: 'Wonyoung', anchor: 5.36 },
          { id: 'TYR0lgLYNVc', type: 'single_face', member: 'Wonyoung', anchor: 5.36 },
          { id: 'LOAhIwZcLgw', type: 'single_full', member: 'Liz', anchor: 5.35 },
          { id: 'jNsCAmy385k', type: 'single_face', member: 'Liz', anchor: 5.69 },
          { id: 'O0uayQ6aXkw', type: 'single_full', member: 'Leeseo', anchor: 5.33 },
          { id: 'yebRuOuP79w', type: 'single_face', member: 'Leeseo', anchor: 5.07 },
        ],
      },
      {
        id: 'iv_230415',
        title: 'Music Core',
        date: '2023. 4. 15.',
        videos: [
          { id: 'r6p5Avk3GG8', type: 'main', anchor: 4.14 },
          { id: 'KC-KkPwyALU', type: 'full', anchor: 5.55 },
          { id: 'li7lQmW_ixU', type: 'single_full', member: 'Yujin', anchor: 6.81 },
          { id: 'T9OVGWtIg8s', type: 'single_face', member: 'Yujin', anchor: 5.05 },
          { id: 'dqoQDnC2stY', type: 'single_full', member: 'Gaeul', anchor: 4.99 },
          { id: 'M3HfYnpyu0g', type: 'single_full', member: 'Wonyoung', anchor: 6.49 },
          { id: 'gfAdmkhQJ4A', type: 'single_face', member: 'Wonyoung', anchor: 4.81 },
          { id: 'etvIfapO-4c', type: 'single_full', member: 'Liz', anchor: 5.09 },
          { id: 'y-ZLmtXZ6xc', type: 'single_face', member: 'Liz', anchor: 4.79 },
          { id: 'ueQApjzIOxE', type: 'single_full', member: 'Leeseo', anchor: 4.85 },
        ],
      },
      {
        id: 'iv_230416',
        title: 'Inkigayo',
        date: '2023. 4. 16.',
        videos: [
          { id: 'HJgWz4p2Wxk', type: 'main', anchor: 9.45 },
          { id: 'tVd361ZM3DI', type: '1take', anchor: 4.78 },
          { id: 'mcINtGENBaI', type: 'tower', anchor: 5.04 },
          { id: 'uJKbN9mDn14', type: 'full', anchor: 4.75 },
          { id: '0fdp6CwPQdQ', type: 'single_full', member: 'Yujin', anchor: 15.19 },
          { id: 'WyjoHMlY5dU', type: 'single_face', member: 'Yujin', anchor: 4.73 },
          { id: 'iDBA20hd7C8', type: 'single_full', member: 'Gaeul', anchor: 9.38 },
          { id: 'JEnAyaPbyWo', type: 'single_face', member: 'Gaeul', anchor: 10.91 },
          { id: 'bp8Y_dGCByA', type: 'single_full', member: 'Wonyoung', anchor: 16.71 },
          { id: 'By527MmexxE', type: 'single_face', member: 'Wonyoung', anchor: 23.83 },
          { id: 'OaniX6kwMe4', type: 'single_full', member: 'Liz', anchor: 21.88 },
          { id: 'TMQ4TyzThjw', type: 'single_face', member: 'Liz', anchor: 4.7 },
          { id: '0F63jhhNGIk', type: 'single_full', member: 'Leeseo', anchor: 6.93 },
          { id: 'gA0KiNalo14', type: 'single_face', member: 'Leeseo', anchor: 4.83 },
        ],
      },
      {
        id: 'iv_230423',
        title: 'Inkigayo',
        date: '2023. 4. 23.',
        videos: [
          { id: 'aeJOyqdsMlU', type: 'main', anchor: 4.82 },
          { id: 'HRQTexfN7GY', type: 'full', anchor: 4.43 },
          { id: 'CeEKboOIYKg', type: 'single_face', member: 'Yujin', anchor: 4.65 },
          { id: '5UrY2OoxkpM', type: 'single_face', member: 'Gaeul', anchor: 4.79 },
          { id: 'r9jO5gID2ks', type: 'single_full', member: 'Wonyoung', anchor: 4.36 },
          { id: 'W4DMbDAeOUU', type: 'single_full', member: 'Liz', anchor: 4.43 },
          { id: 'OPrV4Y1HZfU', type: 'single_full', member: 'Leeseo', anchor: 4.82 },
        ],
      },
    ],
  },
  {
    id: 'lovemelikethis',
    title: 'Love Me Like This',
    group: 'NMIXX',
    album: Expergo,
    anchor: 56.27,
    session: [
      {
        id: 'nm_230323',
        title: 'M COUNTDOWN',
        date: '2023. 3. 23.',
        videos: [
          { id: 'g1UNai7vSPk', type: 'main', anchor: 63.89 },
          { id: 'zJcPaVjVRNo', type: 'full', anchor: 58.7 },
          { id: '2hsNDr0QWNg', type: 'single_full', member: 'Lily', anchor: 58.69 },
          { id: 'th3QPuXlVxM', type: 'single_full', member: 'Haewon', anchor: 58.67 },
          { id: 'nuQ4NHeuSZg', type: 'single_full', member: 'Sullyoon', anchor: 58.67 },
          { id: 'ap8MFdfCTy8', type: 'single_full', member: 'Bae', anchor: 58.67 },
          { id: 'S9800GcCTco', type: 'single_full', member: 'Jiwoo', anchor: 58.68 },
          { id: '_taZJKjNCew', type: 'single_full', member: 'Kyujin', anchor: 58.71 },
        ],
      },
      {
        id: 'nm_230324',
        title: 'Music Bank',
        date: '2023. 3. 24.',
        videos: [
          { id: 'uZQmVZxkPac', type: 'main', anchor: 63.3 },
          { id: 'vQV-m0jDH_A', type: '1take', anchor: 55.77 },
          { id: 'rDt63yhoIH8', type: 'full', anchor: 55.81 },
          { id: 'YVnGvX8eprQ', type: 'single_full', member: 'Lily', anchor: 55.72 },
          { id: 'KFDRy9979Cs', type: 'single_face', member: 'Lily', anchor: 55.48 },
          { id: 'i8_D-5ZkGIc', type: 'single_full', member: 'Haewon', anchor: 55.73 },
          { id: 'ym4ZdDuQt74', type: 'single_face', member: 'Haewon', anchor: 55.82 },
          { id: 'QhNFEPPC_YM', type: 'single_full', member: 'Sullyoon', anchor: 55.74 },
          { id: 'm2E_5U2ZPtQ', type: 'single_face', member: 'Sullyoon', anchor: 55.79 },
          { id: 'aDBqvyiCfHk', type: 'single_full', member: 'Bae', anchor: 55.73 },
          { id: 'nGMLKGPdqZA', type: 'single_face', member: 'Bae', anchor: 55.73 },
          { id: 'RUettmMX8Co', type: 'single_full', member: 'Jiwoo', anchor: 55.73 },
          { id: 'AsAVwaVwDCI', type: 'single_face', member: 'Jiwoo', anchor: 55.78 },
          { id: 'Rv72z91oTTE', type: 'single_full', member: 'Kyujin', anchor: 55.73 },
          { id: 'yM4EGbUUZuw', type: 'single_face', member: 'Kyujin', anchor: 57.44 },
        ],
      },
      {
        id: 'nm_230325',
        title: 'Music Core',
        date: '2023. 3. 25.',
        videos: [
          { id: 'ntBglmH_Hok', type: 'main', anchor: 55.72 },
          { id: '_33bSZ6h_1A', type: 'full', anchor: 55.97 },
          { id: 'e4zmiVRgHuE', type: 'single_full', member: 'Lily', anchor: 58.41 },
          { id: 'gwaKIkD5uZ0', type: 'single_full', member: 'Haewon', anchor: 56.05 },
          { id: 'lqht3KrQga0', type: 'single_face', member: 'Haewon', anchor: 55.8 },
          { id: '6Pv8tjyx22w', type: 'single_full', member: 'Sullyoon', anchor: 55.8 },
          { id: 'XzW1dMAcv-k', type: 'single_face', member: 'Sullyoon', anchor: 55.82 },
          { id: 'v1iPeohKoKg', type: 'single_full', member: 'Bae', anchor: 57.58 },
          { id: 'Ag4L2BUNb-4', type: 'single_face', member: 'Bae', anchor: 56.17 },
          { id: 'nptNrTV85ro', type: 'single_full', member: 'Jiwoo', anchor: 56.51 },
          { id: '9JO1Cz4fqwY', type: 'single_full', member: 'Kyujin', anchor: 56.35 },
        ],
      },
      {
        id: 'nm_230326',
        title: 'Inkigayo',
        date: '2023. 3. 26.',
        videos: [
          { id: 'fy3z55uTBVk', type: 'main', anchor: 60.9 },
          { id: 'mGRq39_OO-I', type: 'full', anchor: 55.98 },
          { id: 'HiGRMuGNe1c', type: 'tower', anchor: 56.64 },
          { id: 'S5-asFuzJUA', type: 'single_full', member: 'Lily', anchor: 57.88 },
          { id: 'EWrLWV2W3sM', type: 'single_full', member: 'Haewon', anchor: 56.06 },
          { id: 'm9lLWqdEAV0', type: 'single_full', member: 'Sullyoon', anchor: 78.29 },
          { id: 'bnNHyTs_qzI', type: 'single_full', member: 'Bae', anchor: 65.91 },
          { id: 'OIUSUqdx3gs', type: 'single_full', member: 'Jiwoo', anchor: 57.95 },
          { id: 'eXYWF-J4f1M', type: 'single_full', member: 'Kyujin', anchor: 64.36 },
        ],
      },
      {
        id: 'nm_230329',
        title: 'Show Champion',
        date: '2023. 3. 29.',
        videos: [
          { id: 'GeenXykTujo', type: 'main', anchor: 56.33 },
          { id: 'UIDAoDXkQzA', type: 'full', anchor: 56.64 },
          { id: 'atJeVSgn5DI', type: 'single_full', member: 'Lily', anchor: 56.64 },
          { id: 'rq2XQYbYTSM', type: 'single_full', member: 'Haewon', anchor: 56.61 },
          { id: '6IjCoBPfm7I', type: 'single_full', member: 'Sullyoon', anchor: 56.63 },
          { id: '2Bc5Ksr4LT8', type: 'single_full', member: 'Bae', anchor: 56.62 },
          { id: 'ly7SSYASVmQ', type: 'single_full', member: 'Jiwoo', anchor: 56.65 },
          { id: 'JgvCD0yScdQ', type: 'single_full', member: 'Kyujin', anchor: 56.67 },
        ],
      },
      {
        id: 'nm_230331',
        title: 'Music Bank',
        date: '2023. 3. 31.',
        videos: [
          { id: '5QSwkSSt0jc', type: 'main', anchor: 70.43 },
          { id: 'sJRsHFt7a5U', type: 'full', anchor: 55.79 },
          { id: 'Qa3UJFUQt88', type: 'single_full', member: 'Lily', anchor: 58.05 },
          { id: 'yLBCnKPnI6A', type: 'single_full', member: 'Haewon', anchor: 58.05 },
          { id: 'gxZcTHTi1fU', type: 'single_full', member: 'Sullyoon', anchor: 58.06 },
          { id: 'nmmmU3qgWtI', type: 'single_face', member: 'Sullyoon', anchor: 56.12 },
          { id: 'ZCLHvlgQIRg', type: 'single_full', member: 'Bae', anchor: 57.99 },
          { id: '-hSsloLq5mY', type: 'single_full', member: 'Jiwoo', anchor: 58.02 },
          { id: 'bFtQjb-I5Mw', type: 'single_full', member: 'Kyujin', anchor: 58.06 },
          { id: 'gwGT48Xs9ak', type: 'single_face', member: 'Kyujin', anchor: 56.38 },
        ],
      },
      {
        id: 'nm_230402',
        title: 'Inkigayo',
        date: '2023. 4. 2.',
        videos: [
          { id: 'VWHaz8n8eq0', type: 'main', anchor: 55.93 },
          { id: '7nsaMbXahx4', type: 'full', anchor: 56.13 },
          { id: 'd9oCxpBV0-w', type: 'single_full', member: 'Lily', anchor: 59.92 },
          { id: 'bmk6cRAE8lc', type: 'single_full', member: 'Haewon', anchor: 66.02 },
          { id: 'KLzc5TUnnK4', type: 'single_face', member: 'Haewon', anchor: 78.26 },
          { id: 'q0F0hrpHxdo', type: 'single_full', member: 'Sullyoon', anchor: 55.9 },
          { id: 'MigXDvkcVoM', type: 'single_face', member: 'Sullyoon', anchor: 75.06 },
          { id: 'jr8XznHNZ9Q', type: 'single_full', member: 'Bae', anchor: 56.01 },
          { id: 'etInrIOjZJ4', type: 'single_full', member: 'Jiwoo', anchor: 67.54 },
          { id: 't7buifTVLn4', type: 'single_face', member: 'Jiwoo', anchor: 59.91 },
          { id: 'VSiH6uJ0Sgo', type: 'single_full', member: 'Kyujin', anchor: 62.8 },
        ],
      },
      {
        id: 'nm_230412',
        title: 'Show Champion',
        date: '2023. 4. 12.',
        videos: [
          { id: 'z0Mga1b_NNI', type: 'main', anchor: 67.9 },
          { id: 'PcQZq_zDNwU', type: 'full', anchor: 56.71 },
          { id: 'hRZ61s3gFPE', type: 'single_full', member: 'Lily', anchor: 56.68 },
          { id: 'BHTE30giMoE', type: 'single_full', member: 'Haewon', anchor: 56.71 },
          { id: 'J6sJubY9yL8', type: 'single_full', member: 'Sullyoon', anchor: 56.72 },
          { id: '2YKzF-fdChQ', type: 'single_full', member: 'Bae', anchor: 56.72 },
          { id: 'pFutUyRXFN8', type: 'single_full', member: 'Jiwoo', anchor: 56.7 },
          { id: '6CxeKIJyf5A', type: 'single_full', member: 'Kyujin', anchor: 56.72 },
        ],
      },
    ],
  },
  {
    id: 'spicy',
    title: 'Spicy',
    group: 'aespa',
    album: MyWorld,
    anchor: 44.16,
    session: [
      {
        id: 'ae_230511',
        title: 'M COUNTDOWN',
        date: '2023. 5. 11.',
        videos: [
          { id: 'k75oGRMiENk', type: 'main', anchor: 78.85 },
          { id: 'jGUXqgH1xvc', type: 'full', anchor: 52.2 },
          { id: 'EX2Q6QTjnsY', type: 'single_full', member: 'Karina', anchor: 45.23 },
          { id: 'kpEbQOzJb00', type: 'single_face', member: 'Karina', anchor: 45.87 },
          { id: 'serGk772VsI', type: 'single_full', member: 'Giselle', anchor: 45.26 },
          { id: '0NoxT6iAJy8', type: 'single_face', member: 'Giselle', anchor: 44.9 },
          { id: '3Ze1041sM7k', type: 'single_full', member: 'Winter', anchor: 45.27 },
          { id: 'em1zsb5OKXM', type: 'single_face', member: 'Winter', anchor: 58.98 },
          { id: '0dyExB3TxlY', type: 'single_full', member: 'Ningning', anchor: 50.79 },
          { id: '5a2NxXWfEks', type: 'single_face', member: 'Ningning', anchor: 44.6 },
        ],
      },
      {
        id: 'ae_230512',
        title: 'Music Bank',
        date: '2023. 5. 12.',
        videos: [
          { id: 'H1c06ycRWaM', type: 'main', anchor: 70.43 },
          { id: 'xWyeg5qYL2I', type: 'full', anchor: 43.52 },
          { id: 'HeF2JRgznOs', type: 'single_full', member: 'Karina', anchor: 44.4 },
          { id: '68thnf9uKUU', type: 'single_face', member: 'Karina', anchor: 43.83 },
          { id: 'FojJBz4LqhY', type: 'single_full', member: 'Giselle', anchor: 44.41 },
          { id: 'pjHxO267AYk', type: 'single_face', member: 'Giselle', anchor: 44.22 },
          { id: '2H2h6ODDbN4', type: 'single_full', member: 'Winter', anchor: 44.4 },
          { id: 'FPvCy4YxZ0w', type: 'single_face', member: 'Winter', anchor: 70.41 },
          { id: 'diPDMNxCoGY', type: 'single_full', member: 'Ningning', anchor: 44.37 },
          { id: '0M-rQwyfIXc', type: 'single_face', member: 'Ningning', anchor: 44.66 },
        ],
      },
      {
        id: 'ae_230513',
        title: 'Music Core',
        date: '2023. 5. 13.',
        videos: [
          { id: 'dJ09BiaovoU', type: 'main', anchor: 44.32 },
          { id: 'NRvqGh6nGWA', type: 'full', anchor: 44.88 },
          { id: 'mO0oHjAnA0A', type: 'single_full', member: 'Karina', anchor: 44.2 },
          { id: 'fswJ9kgKvrY', type: 'single_face', member: 'Karina', anchor: 44.12 },
          { id: 'nDv5t-CiMEw', type: 'single_full', member: 'Giselle', anchor: 44.59 },
          { id: 'g667CEcJy84', type: 'single_face', member: 'Giselle', anchor: 44.95 },
          { id: 'cQ48GtBfqAo', type: 'single_full', member: 'Winter', anchor: 44.52 },
          { id: 'lohKfGOWsSc', type: 'single_face', member: 'Winter', anchor: 46.86 },
          { id: 'RJJ497BQhmI', type: 'single_full', member: 'Ningning', anchor: 44.84 },
          { id: 'WuvBFSkeKsE', type: 'single_face', member: 'Ningning', anchor: 44.46 },
        ],
      },
      {
        id: 'ae_230514',
        title: 'Inkigayo',
        date: '2023. 5. 14.',
        videos: [
          { id: 'FsvzDcfvCW0', type: 'main', anchor: 48.95 },
          { id: '2Fm25bf4fjw', type: 'tower', anchor: 47.44 },
          { id: 'tX3G0yzQqD4', type: '1take', anchor: 46.22 },
          { id: 'Wrw2un78CQs', type: 'full', anchor: 43.92 },
          { id: 'cskrzMWLCms', type: 'single_full', member: 'Karina', anchor: 44.12 },
          { id: 'gpFSXXhonVk', type: 'single_face', member: 'Karina', anchor: 44.32 },
          { id: '21YjIg3XMN0', type: 'single_full', member: 'Giselle', anchor: 44.01 },
          { id: 'a1BF2BBXE2g', type: 'single_face', member: 'Giselle', anchor: 44.39 },
          { id: 'NnUwY5jcrBc', type: 'single_full', member: 'Winter', anchor: 43.96 },
          { id: 'Upc8cmpQNbk', type: 'single_face', member: 'Winter', anchor: 51.14 },
          { id: 'sRPi_lMHUPY', type: 'single_full', member: 'Ningning', anchor: 43.99 },
          { id: '_0ogBPpOaFY', type: 'single_face', member: 'Ningning', anchor: 43.98 },
        ],
      },
      {
        id: 'ae_230518',
        title: 'M COUNTDOWN',
        date: '2023. 5. 18.',
        videos: [
          { id: 'RzeFY37-Mak', type: 'main', anchor: 43.91 },
          { id: 'XbTyYsOUfjE', type: 'full', anchor: 44.11 },
          { id: 'edHydgKcCwQ', type: 'live', anchor: 135.01 },
          { id: 'mQNNCYONyd4', type: 'single_full', member: 'Karina', anchor: 48.19 },
          { id: 'yWm4PtbdxUA', type: 'single_face', member: 'Karina', anchor: 42.45 },
          { id: 'xVR-aHFQTUg', type: 'single_full', member: 'Giselle', anchor: 48.22 },
          { id: 'py_lZZuGucw', type: 'single_full', member: 'Winter', anchor: 48.21 },
          { id: 'RG0PCA8UMIw', type: 'single_full', member: 'Ningning', anchor: 48.18 },
        ],
      },
      {
        id: 'ae_230519',
        title: 'Music Bank',
        date: '2023. 5. 19.',
        videos: [
          { id: 'qKzbdCkRjfA', type: 'main', anchor: 52.5 },
          { id: 'cZDO5oXQHbk', type: 'full', anchor: 44.33 },
          { id: 'qNBWD3FxB8U', type: 'live', anchor: 128.9 },
          { id: 'qehyXtfAjBk', type: 'single_full', member: 'Karina', anchor: 44.32 },
          { id: 'TqBXWlVKXrs', type: 'single_face', member: 'Karina', anchor: 44.61 },
          { id: 'yxiDNkyd3Fs', type: 'single_full', member: 'Giselle', anchor: 44.4 },
          { id: 'VFevjdi5s9w', type: 'single_face', member: 'Giselle', anchor: 44.12 },
          { id: 'pewqJxdVG4E', type: 'single_full', member: 'Winter', anchor: 44.35 },
          { id: 'ETZahO-oHXc', type: 'single_face', member: 'Winter', anchor: 44.15 },
          { id: '4Jhb1W-jcAk', type: 'single_full', member: 'Ningning', anchor: 44.33 },
          { id: 'mmpIGk_zD-o', type: 'single_face', member: 'Ningning', anchor: 44 },
        ],
      },
      {
        id: 'ae_230520',
        title: 'Music Core',
        date: '2023. 5. 20.',
        videos: [
          { id: 'xq7L0A1657I', type: 'main', anchor: 44.23 },
          { id: 'ffJ7suIEM6k', type: 'live', anchor: 112.03 },
          { id: '3pmaDofPC4c', type: 'full', anchor: 44.29 },
          { id: 'CQTe26dANK4', type: 'single_full', member: 'Karina', anchor: 43.9 },
          { id: 'PZRe_Syi2pY', type: 'single_face', member: 'Karina', anchor: 43.93 },
          { id: 'rZ1-jE6qeTI', type: 'single_full', member: 'Giselle', anchor: 44.25 },
          { id: '_2XPrCD8TaY', type: 'single_face', member: 'Giselle', anchor: 45.15 },
          { id: 'noV57PLcvKg', type: 'single_full', member: 'Winter', anchor: 44.03 },
          { id: '2lbTFJi91z8', type: 'single_face', member: 'Winter', anchor: 44.23 },
          { id: 'v06p_YioTf8', type: 'single_full', member: 'Ningning', anchor: 44.65 },
          { id: '8TP3ykBJbm0', type: 'single_face', member: 'Ningning', anchor: 53.98 },
        ],
      },
      {
        id: 'ae_230521',
        title: 'Inkigayo',
        date: '2023. 5. 21.',
        videos: [
          { id: 'rC4McQfRCBA', type: 'main', anchor: 44.02 },
          { id: 'ghFFHNUsvEM', type: 'live', anchor: 95.8 },
          { id: 'vr4usgQNfUM', type: 'full', anchor: 43.91 },
          { id: '6cWRzhHebqM', type: 'single_full', member: 'Karina', anchor: 43.91 },
          { id: '5ErG8C-f_LQ', type: 'single_face', member: 'Karina', anchor: 66.77 },
          { id: 'OJjMP5GQyd4', type: 'single_full', member: 'Giselle', anchor: 62.02 },
          { id: 'Vbh2wrYJjPQ', type: 'single_face', member: 'Giselle', anchor: 43.93 },
          { id: 'RGOGEKvHRBY', type: 'single_full', member: 'Winter', anchor: 60.83 },
          { id: 'KdFdSj6XxbA', type: 'single_face', member: 'Winter', anchor: 58.35 },
          { id: 'HsaOeu7Hkt0', type: 'single_full', member: 'Ningning', anchor: 43.98 },
          { id: '77iyTi75pXc', type: 'single_face', member: 'Ningning', anchor: 43.95 },
        ],
      },
    ],
  },
  {
    id: 'unforgiven',
    title: 'UNFORGIVEN',
    group: 'LE SSERAFIM',
    album: Unforgiven,
    anchor: 38.91,
    session: [
      {
        id: 'ls_230501',
        title: 'LE SSERAFIM COMEBACK SHOW',
        date: '2023. 5. 1.',
        videos: [
          { id: 'wIBZ7UcQmDU', type: 'main', anchor: 38.61 },
          { id: 'LDqF_yMNCGY', type: 'full', anchor: 38.7 },
          { id: 'FxpXCSaZ7CY', type: 'single_full', member: 'Sakura', anchor: 37.92 },
          { id: 'a5OMVlV2Xjo', type: 'single_face', member: 'Sakura', anchor: 43.81 },
          { id: 'tZkDJaa4NLc', type: 'single_full', member: 'Chaewon', anchor: 53.38 },
          { id: 'jCMT4v6JI9Q', type: 'single_face', member: 'Chaewon', anchor: 40.62 },
          { id: 'f4qXdspu8l0', type: 'single_full', member: 'Yunjin', anchor: 37.88 },
          { id: 'uOzzwLuqCGs', type: 'single_face', member: 'Yunjin', anchor: 39.3 },
          { id: '6Dpytb_iK7I', type: 'single_full', member: 'Kazuha', anchor: 37.89 },
          { id: 'xuA50KI8_S8', type: 'single_face', member: 'Kazuha', anchor: 70.48 },
          { id: '4zhjecfJs6o', type: 'single_full', member: 'Eunchae', anchor: 49.69 },
          { id: 'p8tbt9MbUdY', type: 'single_face', member: 'Eunchae', anchor: 40.59 },
        ],
      },
      {
        id: 'ls_230504',
        title: 'M COUNTDOWN',
        date: '2023. 5. 4.',
        videos: [
          { id: 'AubkK9-bOUY', type: 'main', anchor: 84.89 },
          { id: 'GpiB_b7h6a0', type: 'full', anchor: 46.27 },
          { id: '6J4jZ42Mt4U', type: 'single_full', member: 'Sakura', anchor: 39.62 },
          { id: 'ZAdPWGLBjoQ', type: 'single_face', member: 'Sakura', anchor: 38.7 },
          { id: 'Sy_f0_Y3HZM', type: 'single_full', member: 'Chaewon', anchor: 39.65 },
          { id: 'bC4dV9xsTwQ', type: 'single_face', member: 'Chaewon', anchor: 38.96 },
          { id: 'Z3QLQ3gKjug', type: 'single_full', member: 'Yunjin', anchor: 43.17 },
          { id: 'Yb95VFCnIvk', type: 'single_full', member: 'Kazuha', anchor: 47.13 },
          { id: 'uX-zjSxyckA', type: 'single_full', member: 'Eunchae', anchor: 39.67 },
        ],
      },
      {
        id: 'ls_230505',
        title: 'Music Bank',
        date: '2023. 5. 5.',
        videos: [
          { id: 'WOuReoE8Yq0', type: 'main', anchor: 93.61 },
          { id: 'cGwJx9nkrwI', type: 'full', anchor: 38.67 },
          { id: '-8yllhAe2BE', type: '1take', anchor: 39.2 },
          { id: 'DZtKT1yw9mo', type: 'single_full', member: 'Sakura', anchor: 39.11 },
          { id: 'HuD1spqgJ44', type: 'single_face', member: 'Sakura', anchor: 38.76 },
          { id: 'jjd9K_tC1-E', type: 'single_full', member: 'Chaewon', anchor: 39.13 },
          { id: 'QvwaMSxLfDc', type: 'single_face', member: 'Chaewon', anchor: 38.46 },
          { id: '-JNs5yvz7xw', type: 'single_full', member: 'Yunjin', anchor: 39.17 },
          { id: '4CjWTPBJLf8', type: 'single_face', member: 'Yunjin', anchor: 39.33 },
          { id: '49_uJrKrVrs', type: 'single_full', member: 'Kazuha', anchor: 39.17 },
          { id: 'Dd6O7DHhbSw', type: 'single_face', member: 'Kazuha', anchor: 37.93 },
          { id: '6xL6Cj_aQto', type: 'single_full', member: 'Eunchae', anchor: 39.14 },
          { id: 'osR2cbPerRk', type: 'single_face', member: 'Eunchae', anchor: 54.02 },
        ],
      },
      {
        id: 'ls_230507',
        title: 'Inkigayo',
        date: '2023. 5. 7.',
        videos: [
          { id: 'rHri4okJEBs', type: 'main', anchor: 104.37 },
          { id: '1nOlI176Hyg', type: 'tower', anchor: 38.09 },
          { id: 'WUJYt4Zs3Ko', type: '1take', anchor: 37.5 },
          { id: 'S58ajuWh4HA', type: 'full', anchor: 85.3 },
          { id: 'kF-uVLR5xNA', type: 'single_full', member: 'Sakura', anchor: 86.71 },
          { id: 'STXOL0Ly7WY', type: 'single_face', member: 'Sakura', anchor: 37.81 },
          { id: 'co_WN6iz7xs', type: 'single_full', member: 'Chaewon', anchor: 86.46 },
          { id: 'pZhgbQNy31s', type: 'single_face', member: 'Chaewon', anchor: 38.23 },
          { id: 'IQAlk34lsu4', type: 'single_full', member: 'Yunjin', anchor: 87.03 },
          { id: 'p3v64opQSU0', type: 'single_face', member: 'Yunjin', anchor: 37.89 },
          { id: 'xOy_e_syD-0', type: 'single_full', member: 'Kazuha', anchor: 87.06 },
          { id: 'MkYV_gjKORQ', type: 'single_face', member: 'Kazuha', anchor: 37.7 },
          { id: '-KRKCSYD6-Q', type: 'single_full', member: 'Eunchae', anchor: 91.61 },
          { id: 'AOdh68qz7TI', type: 'single_face', member: 'Eunchae', anchor: 37.59 },
        ],
      },
      {
        id: 'ls_230510',
        title: 'Show Champion',
        date: '2023. 5. 10.',
        videos: [
          { id: '3gqxGCMKA6w', type: 'main', anchor: 57.65 },
          { id: 'vQFrNHDaCPg', type: 'full', anchor: 39.01 },
          { id: 'ZxB17VR3Xpg', type: 'single_full', member: 'Sakura', anchor: 39.06 },
          { id: 'BRLeHVAqYeE', type: 'single_face', member: 'Sakura', anchor: 39.02 },
          { id: 'gfKmYQLXEWM', type: 'single_full', member: 'Chaewon', anchor: 39.02 },
          { id: '5q91u_b0GnA', type: 'single_face', member: 'Chaewon', anchor: 39.11 },
          { id: '4HKO_GVqbcM', type: 'single_full', member: 'Yunjin', anchor: 39.09 },
          { id: 'oo4UXhBq8Yo', type: 'single_full', member: 'Kazuha', anchor: 39.04 },
          { id: 'JqrrLvN3QHc', type: 'single_face', member: 'Kazuha', anchor: 39.04 },
          { id: 'CdlLy5W4Wgw', type: 'single_full', member: 'Eunchae', anchor: 39.07 },
        ],
      },
      {
        id: 'ls_230511',
        title: 'M COUNTDOWN',
        date: '2023. 5. 11.',
        videos: [
          { id: 'ZEUFAV9jmGk', type: 'main', anchor: 39.62 },
          { id: '5Ppi5gTt7EE', type: 'full', anchor: 38.75 },
          { id: 'OvVCeytc3i0', type: 'live', anchor: 119.5 },
          { id: 'byH0Y5ZSgko', type: 'single_full', member: 'Sakura', anchor: 41.82 },
          { id: 'S5uxTbC_-8A', type: 'single_full', member: 'Chaewon', anchor: 38.94 },
          { id: 'fvGr77ClRtQ', type: 'single_full', member: 'Kazuha', anchor: 38.89 },
        ],
      },
      {
        id: 'ls_230512',
        title: 'Music Bank',
        date: '2023. 5. 12.',
        videos: [
          { id: '1bir8XbmtZ4', type: 'main', anchor: 37.82 },
          { id: 'M_AYlwtRJ2M', type: 'full', anchor: 38.84 },
          { id: 'zYTq5Wvy2No', type: 'live', anchor: 121.91 },
          { id: 'WxDfybynccI', type: 'single_full', member: 'Sakura', anchor: 38.87 },
          { id: '7qaEbFzb8yM', type: 'single_face', member: 'Sakura', anchor: 38.39 },
          { id: 'eRRQjCDdZWM', type: 'single_full', member: 'Chaewon', anchor: 38.9 },
          { id: 'kG-ZKwW6odQ', type: 'single_full', member: 'Yunjin', anchor: 38.91 },
          { id: 'wwzTzrZuQY0', type: 'single_face', member: 'Yunjin', anchor: 37.67 },
          { id: 'ta_XQKHRB1o', type: 'single_full', member: 'Kazuha', anchor: 38.87 },
          { id: 'ZC7jN9tcrU0', type: 'single_full', member: 'Eunchae', anchor: 38.85 },
        ],
      },
      {
        id: 'ls_230514',
        title: 'Inkigayo',
        date: '2023. 5. 14.',
        videos: [
          { id: '8yL7Pz8S-Qk', type: 'main', anchor: 39.57 },
          { id: 'SAja_iEkv-4', type: 'live', anchor: 123.96 },
          { id: 'sl7llriAi90', type: 'full', anchor: 38.61 },
          { id: 'Vq8wwmneRU8', type: 'single_full', member: 'Sakura', anchor: 38.47 },
          { id: 'eRdSxhAzcPU', type: 'single_face', member: 'Sakura', anchor: 38.54 },
          { id: '2fGuqx3CHVQ', type: 'single_face', member: 'Chaewon', anchor: 39.06 },
          { id: '1Wg2dBOuYpc', type: 'single_full', member: 'Yunjin', anchor: 38.51 },
          { id: '8PdLkbgme8g', type: 'single_face', member: 'Kazuha', anchor: 38.42 },
          { id: '10kyZCRj79Y', type: 'single_full', member: 'Eunchae', anchor: 38.75 },
        ],
      },
      {
        id: 'ls_230518',
        title: 'M COUNTDOWN',
        date: '2023. 5. 18.',
        videos: [
          { id: 'mlkWvQ7OYCw', type: 'main', anchor: 39.48 },
          { id: 'LnnGpi3bE8k', type: 'full', anchor: 40.31 },
          { id: 'w0ugxrLMauw', type: 'single_full', member: 'Sakura', anchor: 38.27 },
          { id: '_M20iVjed9I', type: 'single_full', member: 'Chaewon', anchor: 52.48 },
          { id: 'O3SEGumuvcY', type: 'single_full', member: 'Yunjin', anchor: 38.3 },
          { id: 'p7HQex3ThsM', type: 'single_full', member: 'Kazuha', anchor: 38.26 },
          { id: 'bISKFQZqeSQ', type: 'single_full', member: 'Eunchae', anchor: 38.26 },
        ],
      },
      {
        id: 'ls_230519',
        title: 'Music Bank',
        date: '2023. 5. 19.',
        videos: [
          { id: 'OM3jNNhsLr4', type: 'main', anchor: 49.66 },
          { id: 'jEwaprV6BtY', type: 'full', anchor: 37.85 },
          { id: 'rdHHs2jY82g', type: 'single_full', member: 'Sakura', anchor: 37.84 },
          { id: 'lch7E63mXRM', type: 'single_full', member: 'Chaewon', anchor: 37.86 },
          { id: 'GngbPpFFzbI', type: 'single_full', member: 'Yunjin', anchor: 37.83 },
          { id: 'S8ZEJ7x0578', type: 'single_full', member: 'Kazuha', anchor: 37.87 },
          { id: 'wj3JEGJoi2E', type: 'single_full', member: 'Eunchae', anchor: 37.87 },
        ],
      },
      {
        id: 'ls_230521',
        title: 'Inkigayo',
        date: '2023. 5. 21.',
        videos: [
          { id: 'EX2079C0PbQ', type: 'main', anchor: 38.07 },
          { id: 'LunDAAjpjhM', type: 'full', anchor: 38.46 },
          { id: '3vv6_sIiMCg', type: 'single_full', member: 'Sakura', anchor: 45.2 },
          { id: 'Q7pR7uazGgU', type: 'single_face', member: 'Sakura', anchor: 47.45 },
          { id: '5YdbNUVSXWo', type: 'single_full', member: 'Chaewon', anchor: 38.52 },
          { id: 'nKBvUqCrzIg', type: 'single_full', member: 'Yunjin', anchor: 49.35 },
          { id: 'H9uol1xbnKE', type: 'single_face', member: 'Yunjin', anchor: 44.4 },
          { id: 'VnwSvj6p8mQ', type: 'single_full', member: 'Kazuha', anchor: 44.82 },
          { id: 'FEaKSS1S9RM', type: 'single_full', member: 'Eunchae', anchor: 38.51 },
          { id: 'Aq-_7P8FOLs', type: 'single_face', member: 'Eunchae', anchor: 38.1 },
        ],
      },
    ],
  },
  {
    id: 'omg',
    title: 'OMG',
    group: 'NewJeans',
    album: Omg,
    anchor: 45.35,
    session: [
      {
        id: 'nj_230115',
        title: 'Inkigayo',
        date: '2023. 1. 15.',
        videos: [
          { id: '-p1ftgMVWOc', type: 'main', anchor: 79.84 },
          { id: '20mMVe-gEPs', type: 'live', anchor: 40.86 },
          { id: 'Nbw92qgezis', type: '1take', anchor: 45.5 },
          { id: '_kYNYB-79GY', type: 'tower', anchor: 49.71 },
          { id: 'P-mB4-MU-Fk', type: 'full', anchor: 45.23 },
          { id: 'nMAC0IweGDE', type: 'single_full', member: 'Minji', anchor: 55.18 },
          { id: 'A81VEEvyOSI', type: 'single_face', member: 'Minji', anchor: 49.17 },
          { id: '60RaggLgggE', type: 'single_full', member: 'Hanni', anchor: 55.86 },
          { id: 'dIaR5Z4Gwig', type: 'single_face', member: 'Hanni', anchor: 62.62 },
          { id: 'MgVP1_So8H0', type: 'single_full', member: 'Danielle', anchor: 63.54 },
          { id: 'P4eUzN3zlZM', type: 'single_face', member: 'Danielle', anchor: 44.72 },
          { id: 'JBwIdrir5vw', type: 'single_full', member: 'Haerin', anchor: 78.91 },
          { id: 'J8_56-8eSDU', type: 'single_face', member: 'Haerin', anchor: 55.96 },
          { id: 'ZMP83AqwP_U', type: 'single_full', member: 'Hyein', anchor: 74.67 },
          { id: '3knHZe4mBpU', type: 'single_face', member: 'Hyein', anchor: 90.1 },
        ],
      },
      {
        id: 'nj_230120',
        title: 'Music Bank',
        date: '2023. 1. 20.',
        videos: [
          { id: 'X8jjlicVUyY', type: 'main', anchor: 51.8 },
          { id: 'muu73N0z1nM', type: 'full', anchor: 46.59 },
          { id: '0R-tkdX8UUw', type: '1take', anchor: 46.61 },
          { id: 'AtdcdwkCnRs', type: 'single_full', member: 'Minji', anchor: 46.59 },
          { id: 'Dvlm5v8j5kA', type: 'single_face', member: 'Minji', anchor: 45.52 },
          { id: 'EH5Nc_GKdsw', type: 'single_full', member: 'Hanni', anchor: 46.7 },
          { id: 'WZylfvnkk74', type: 'single_face', member: 'Hanni', anchor: 45.5 },
          { id: 'YOzmn9KVZTI', type: 'single_full', member: 'Danielle', anchor: 46.66 },
          { id: 'a4V7gDnEBZs', type: 'single_face', member: 'Danielle', anchor: 53.8 },
          { id: '0HcxRYs51Ys', type: 'single_full', member: 'Haerin', anchor: 46.65 },
          { id: '1BaPtyQ5bY0', type: 'single_face', member: 'Haerin', anchor: 81.02 },
          { id: 'GQAqjPsaMWQ', type: 'single_full', member: 'Hyein', anchor: 46.61 },
          { id: 'gHdP38vubz4', type: 'single_face', member: 'Hyein', anchor: 46.79 },
        ],
      },
      {
        id: 'nj_230127',
        title: 'Music Bank',
        date: '2023. 1. 27.',
        videos: [
          { id: '6bVUjsUi9sw', type: 'main', anchor: 45.54 },
          { id: '9So5ylLoSoA', type: 'full', anchor: 45.57 },
          { id: 'lSUb1DtZ1c4', type: 'live', anchor: 168.17 },
          { id: '0Q62FgVvxLU', type: 'single_full', member: 'Minji', anchor: 45.49 },
          { id: 'oPh78hhPJWI', type: 'single_face', member: 'Minji', anchor: 45.55 },
          { id: '1pzZ514WE3E', type: 'single_full', member: 'Hanni', anchor: 45.47 },
          { id: 'EQUHbbNVghM', type: 'single_face', member: 'Hanni', anchor: 66.06 },
          { id: 'JU5Ks9sF__k', type: 'single_full', member: 'Danielle', anchor: 45.49 },
          { id: 'JH_jGv_tRew', type: 'single_full', member: 'Haerin', anchor: 45.52 },
          { id: 'mQ4oxIhiwZ0', type: 'single_face', member: 'Haerin', anchor: 45.53 },
          { id: 'aLXPqB2CwP0', type: 'single_full', member: 'Hyein', anchor: 45.5 },
        ],
      },
      {
        id: 'nj_230129',
        title: 'Inkigayo',
        date: '2023. 1. 29.',
        videos: [
          { id: 'jUmeh5yvy0M', type: 'main', anchor: 45.67 },
          { id: '7b2Nbr34BW4', type: '1take', anchor: 45.46 },
          { id: '6x1DXe5YZzo', type: 'full', anchor: 45.29 },
          { id: 'abmstlxDQ2I', type: 'single_full', member: 'Minji', anchor: 56.65 },
          { id: 'OdEnLDiTawA', type: 'single_face', member: 'Minji', anchor: 49.79 },
          { id: 'sE5xyyULyjQ', type: 'single_full', member: 'Hanni', anchor: 64.61 },
          { id: 'ZIyLmfF2PMY', type: 'single_face', member: 'Hanni', anchor: 61.25 },
          { id: 'NDTuPvEvVRI', type: 'single_full', member: 'Danielle', anchor: 52.8 },
          { id: 'g5awlKNvOK8', type: 'single_full', member: 'Haerin', anchor: 57.38 },
          { id: 'PUZDbMcYPxg', type: 'single_face', member: 'Haerin', anchor: 53.69 },
          { id: 'wh3pyf5lmH0', type: 'single_full', member: 'Hyein', anchor: 58.83 },
        ],
      },
    ],
  },
  {
    id: 'teddybear',
    title: 'Teddy Bear',
    group: 'STAYC',
    album: TeddyBear,
    anchor: 8.01,
    session: [
      {
        id: 'sc_230216',
        title: 'M COUNTDOWN',
        date: '2023. 2. 16.',
        videos: [
          { id: 'midOBwzGeOM', type: 'main', anchor: 16.19 },
          { id: 'nmPcIDqk9zY', type: 'full', anchor: 10.06 },
          { id: 'joC9fnAs5C0', type: 'single_full', member: 'Sumin', anchor: 8.24 },
          { id: 'OBfG2aB9Rg0', type: 'single_full', member: 'Sieun', anchor: 8.23 },
          { id: 'S3qZqmA6qWs', type: 'single_face', member: 'Sieun', anchor: 9.78 },
          { id: '-jdfF6QzbfQ', type: 'single_full', member: 'Isa', anchor: 8.24 },
          { id: 'jjxqVi9HHIk', type: 'single_full', member: 'Seeun', anchor: 8.26 },
          { id: '1Vk-fkDtv1o', type: 'single_face', member: 'Seeun', anchor: 14.19 },
          { id: 'zEzNAKsVc9E', type: 'single_full', member: 'Yoon', anchor: 8.25 },
          { id: '5fjBIlEfjcQ', type: 'single_full', member: 'J', anchor: 8.22 },
        ],
      },
      {
        id: 'sc_230217',
        title: 'Music Bank',
        date: '2023. 2. 17.',
        videos: [
          { id: '5TKz7HyKius', type: 'main', anchor: 13.62 },
          { id: 'EhmZ3La37Fc', type: 'full', anchor: 8.69 },
          { id: 'ovni5C-AoQ4', type: 'single_full', member: 'Sumin', anchor: 8.66 },
          { id: 'ZTk7yeCnEcw', type: 'single_face', member: 'Sumin', anchor: 78.66 },
          { id: 'bxu0Cct4Pjg', type: 'single_full', member: 'Sieun', anchor: 8.62 },
          { id: 'r25_l-XcR0w', type: 'single_face', member: 'Sieun', anchor: 8.39 },
          { id: 'qEt4bEBD3-8', type: 'single_full', member: 'Isa', anchor: 8.61 },
          { id: '1cPDCMuvaw8', type: 'single_face', member: 'Isa', anchor: 13.37 },
          { id: 'PTNRQsRs_dM', type: 'single_full', member: 'Seeun', anchor: 8.65 },
          { id: 'iUQs5Ae7k2M', type: 'single_face', member: 'Seeun', anchor: 44.95 },
          { id: 'VdN1EVZ8Lis', type: 'single_full', member: 'Yoon', anchor: 8.65 },
          { id: '1m5Y3HbwpAg', type: 'single_face', member: 'Yoon', anchor: 31.87 },
          { id: 'XhYEwpQfz7g', type: 'single_full', member: 'J', anchor: 8.67 },
          { id: 'VixvSNj8rvk', type: 'single_face', member: 'J', anchor: 8.24 },
        ],
      },
      {
        id: 'sc_230218',
        title: 'Music Core',
        date: '2023. 2. 18.',
        videos: [
          { id: 'JzFWveWGASo', type: 'main', anchor: 8.18 },
          { id: '0BQ7OkF3mU0', type: 'full', anchor: 8.54 },
          { id: 'IVzYYkCZi6A', type: 'single_full', member: 'Sumin', anchor: 8.03 },
          { id: 'gk0ePq7qUkI', type: 'single_face', member: 'Sumin', anchor: 8.51 },
          { id: 'o9S-UNDCIlM', type: 'single_full', member: 'Sieun', anchor: 7.9 },
          { id: 'R0uHQqtUi98', type: 'single_full', member: 'Isa', anchor: 8.21 },
          { id: 'P0QqK71R0zU', type: 'single_face', member: 'Isa', anchor: 8.14 },
          { id: 'm5Hmsilcv2M', type: 'single_full', member: 'Seeun', anchor: 8.23 },
          { id: 'V3sF6cn75jI', type: 'single_face', member: 'Seeun', anchor: 8.25 },
          { id: 'RfmTehCOrN0', type: 'single_full', member: 'Yoon', anchor: 8.06 },
          { id: 'rjCPqoQzC5g', type: 'single_full', member: 'J', anchor: 8.46 },
        ],
      },
      {
        id: 'sc_230219',
        title: 'Inkigayo',
        date: '2023. 2. 19.',
        videos: [
          { id: 'Rc2-mJP_tic', type: 'main', anchor: 14.46 },
          { id: 'bMo-lAkEoXM', type: 'full', anchor: 22.57 },
          { id: 'C_niOevYKhM', type: '1take', anchor: 8.19 },
          { id: 'gVe51DKUPB4', type: 'single_full', member: 'Sumin', anchor: 14.31 },
          { id: 'nc1r8d8sevs', type: 'single_face', member: 'Sumin', anchor: 17.8 },
          { id: '91cmyhOT8ew', type: 'single_full', member: 'Sieun', anchor: 12.82 },
          { id: 'Cmfgi1ab8ic', type: 'single_face', member: 'Sieun', anchor: 8.14 },
          { id: 'SCG32c8Huxg', type: 'single_full', member: 'Isa', anchor: 71.67 },
          { id: 'XMKl0fR83Hc', type: 'single_face', member: 'Isa', anchor: 48.02 },
          { id: 'QEWMONISwPc', type: 'single_full', member: 'Seeun', anchor: 11.14 },
          { id: 'VDkaYuWfkvI', type: 'single_face', member: 'Seeun', anchor: 31.02 },
          { id: 'BKG0RiQG21M', type: 'single_full', member: 'Yoon', anchor: 81.38 },
          { id: 'muoERu9kw3U', type: 'single_face', member: 'Yoon', anchor: 69.51 },
          { id: 'OO0FZMM2zwc', type: 'single_full', member: 'J', anchor: 16.1 },
          { id: 'pVLr7dRUx90', type: 'single_face', member: 'J', anchor: 27.98 },
        ],
      },
      {
        id: 'sc_230222',
        title: 'Show Champion',
        date: '2023. 2. 22.',
        videos: [
          { id: 'GN-DRgLs8xI', type: 'main', anchor: 18.61 },
          { id: '6sLcN8GIX9w', type: 'full', anchor: 9.1 },
          { id: '3uZ6LkXDGuU', type: 'single_full', member: 'Sumin', anchor: 9.09 },
          { id: 'gi7PzB9aw-E', type: 'single_full', member: 'Sieun', anchor: 9.12 },
          { id: 'Ps10DG_ugbw', type: 'single_full', member: 'Isa', anchor: 9.13 },
          { id: 'vFpCXPsNSHs', type: 'single_full', member: 'Seeun', anchor: 9.09 },
          { id: '6BzRhzMjI0A', type: 'single_full', member: 'Yoon', anchor: 9.06 },
          { id: 'u14bTcOwoSI', type: 'single_full', member: 'J', anchor: 9.11 },
        ],
      },
      {
        id: 'sc_230223',
        title: 'M COUNTDOWN',
        date: '2023. 2. 23.',
        videos: [
          { id: 'PhJXq3ONIyc', type: 'main', anchor: 9.78 },
          { id: 'vWJyxu2-sHo', type: 'full', anchor: 15.19 },
          { id: 'jhPODew99bg', type: 'single_full', member: 'Sumin', anchor: 8.06 },
          { id: '_3xpymW7J3k', type: 'single_full', member: 'Sieun', anchor: 8.04 },
          { id: 'xzVrkrXgr0Q', type: 'single_full', member: 'Isa', anchor: 8.03 },
          { id: 'Pjz2S8s6PaU', type: 'single_full', member: 'Seeun', anchor: 8.04 },
          { id: 'gMZipjhtiMQ', type: 'single_full', member: 'Yoon', anchor: 8.07 },
          { id: 'w7LYirgmSIY', type: 'single_full', member: 'J', anchor: 8.02 },
        ],
      },
      {
        id: 'sc_230224',
        title: 'Music Bank',
        date: '2023. 2. 24.',
        videos: [
          { id: 'CibadCA9j24', type: 'main', anchor: 21.11 },
          { id: 'num_08QJX00', type: 'full', anchor: 9.2 },
          { id: 'OHIYkzJutRs', type: 'live', anchor: 147.67 },
          { id: 'r5C5LRDADjg', type: 'single_full', member: 'Sumin', anchor: 9.15 },
          { id: 'vHGD_PXgj-s', type: 'single_face', member: 'Sumin', anchor: 13.06 },
          { id: 'mgYSoU8PLZQ', type: 'single_full', member: 'Sieun', anchor: 9.16 },
          { id: '3hIO-083tiE', type: 'single_full', member: 'Isa', anchor: 9.16 },
          { id: 'OajPNTJdAwI', type: 'single_face', member: 'Isa', anchor: 8.66 },
          { id: 'qTftDoszHJc', type: 'single_full', member: 'Seeun', anchor: 9.18 },
          { id: '7NK0iTC6qNs', type: 'single_full', member: 'Yoon', anchor: 9.21 },
          { id: 'GzfKhDN_Lj8', type: 'single_full', member: 'J', anchor: 9.17 },
        ],
      },
      {
        id: 'sc_230225',
        title: 'Music Core',
        date: '2023. 2. 25.',
        videos: [
          { id: 'l_1ivRxUc9I', type: 'main', anchor: 8.03 },
          { id: 'Xy-HFjMpm7Q', type: 'full', anchor: 8.29 },
          { id: '_nWjQq5WItA', type: 'single_full', member: 'Sumin', anchor: 8.27 },
          { id: 'xDLruAKH8Bw', type: 'single_full', member: 'Sieun', anchor: 8.25 },
          { id: 's4BjnIBJw6A', type: 'single_full', member: 'Isa', anchor: 8.28 },
          { id: '7OKeVuNTIko', type: 'single_full', member: 'Seeun', anchor: 8.96 },
          { id: 'PraQy1lgUvI', type: 'single_full', member: 'Yoon', anchor: 8.75 },
          { id: 'H6oiLYVqUGw', type: 'single_full', member: 'J', anchor: 8.39 },
        ],
      },
      {
        id: 'sc_230226',
        title: 'Inkigayo',
        date: '2023. 2. 26.',
        videos: [
          { id: '-IJjf9HxO-A', type: 'main', anchor: 8.72 },
          { id: 'amoM9SKVVMk', type: 'full', anchor: 8.18 },
          { id: 'RpgeK0-zw4o', type: 'live', anchor: 121.51 },
          { id: '93A0ykOhkf4', type: 'single_full', member: 'Sumin', anchor: 23.57 },
          { id: '5xXyWlrQ8wo', type: 'single_face', member: 'Sumin', anchor: 24.82 },
          { id: 'Zp1PJz-lNE0', type: 'single_full', member: 'Sieun', anchor: 12.83 },
          { id: 'NmUL445JG7o', type: 'single_full', member: 'Isa', anchor: 29.32 },
          { id: 'ZGwHj6-Lcwo', type: 'single_face', member: 'Isa', anchor: 28.74 },
          { id: 'HyGP-wuk-g4', type: 'single_full', member: 'Seeun', anchor: 35.92 },
          { id: '_FYMIU7Q2cE', type: 'single_face', member: 'Seeun', anchor: 22.48 },
          { id: 'kAjKTTS9EGs', type: 'single_full', member: 'Yoon', anchor: 12.16 },
          { id: 'iiS3-LH_Eqk', type: 'single_face', member: 'Yoon', anchor: 41.16 },
          { id: 'u5lrhiuQmGM', type: 'single_full', member: 'J', anchor: 33.43 },
        ],
      },
      {
        id: 'sc_230301',
        title: 'Show Champion',
        date: '2023. 3. 1.',
        videos: [
          { id: 'QwOzgeO7__I', type: 'main', anchor: 8.45 },
          { id: 'Rle4gMqRvRM', type: 'full', anchor: 9.08 },
          { id: 'qyZfwjrBld0', type: 'single_full', member: 'Sumin', anchor: 9.08 },
          { id: 'zekmYPc5Wyg', type: 'single_full', member: 'Sieun', anchor: 9.13 },
          { id: 'zN1li87TvkQ', type: 'single_full', member: 'Isa', anchor: 9.08 },
          { id: 'x517t6YRMOA', type: 'single_full', member: 'Seeun', anchor: 9.08 },
          { id: '9Y58CGoN0Hk', type: 'single_full', member: 'Yoon', anchor: 9.07 },
          { id: 'lv61442Eef0', type: 'single_full', member: 'J', anchor: 9.07 },
        ],
      },
      {
        id: 'sc_230303',
        title: 'Music Bank',
        date: '2023. 3. 3.',
        videos: [
          { id: 'TRpxC_4Yw9A', type: 'main', anchor: 20.13 },
          { id: 'bdvZSoM3tZo', type: 'full', anchor: 8.02 },
          { id: 'qka7tqUJsv8', type: 'single_full', member: 'Sumin', anchor: 8.98 },
          { id: 'iNK2tEl0WZw', type: 'single_full', member: 'Sieun', anchor: 9.02 },
          { id: 'cPkdlSuaebY', type: 'single_full', member: 'Isa', anchor: 9.06 },
          { id: 'sv34zOmPzgE', type: 'single_full', member: 'Seeun', anchor: 9.06 },
          { id: 'TTERdj1qN0s', type: 'single_full', member: 'Yoon', anchor: 8.99 },
          { id: 'ZEQJiBUcUh8', type: 'single_full', member: 'J', anchor: 9.03 },
        ],
      },
      {
        id: 'sc_230304',
        title: 'Music Core',
        date: '2023. 3. 4.',
        videos: [
          { id: 'DTG04YNkocM', type: 'main', anchor: 8 },
          { id: '9Vx6P7GTOdY', type: 'full', anchor: 8.63 },
          { id: 'zuP-6gw-XZk', type: 'single_full', member: 'Sumin', anchor: 8.47 },
          { id: 'gzX2oX_vanc', type: 'single_full', member: 'Sieun', anchor: 8.54 },
          { id: 'F2YZ6stf4aU', type: 'single_full', member: 'Isa', anchor: 8.82 },
          { id: 'rli-7_4EEKw', type: 'single_full', member: 'Seeun', anchor: 8.8 },
          { id: 'j7wyz3oC-ts', type: 'single_full', member: 'Yoon', anchor: 8.57 },
          { id: '_Pdo9fTosJQ', type: 'single_full', member: 'J', anchor: 8.26 },
        ],
      },
      {
        id: 'sc_230308',
        title: 'Show Champion',
        date: '2023. 3. 8.',
        videos: [
          { id: 'w8rLN2bBLIM', type: 'main', anchor: 8.29 },
          { id: 'xxRHretCNB8', type: 'full', anchor: 9.1 },
          { id: 'Y5aNhZmkhTg', type: 'single_full', member: 'Sumin', anchor: 9.07 },
          { id: '59Iwwgfp38g', type: 'single_full', member: 'Sieun', anchor: 9.07 },
          { id: '8gb-phRik_4', type: 'single_full', member: 'Isa', anchor: 9.06 },
          { id: 'O0zdjiMw6ro', type: 'single_full', member: 'Seeun', anchor: 9.07 },
          { id: 'aYzLkknvxA8', type: 'single_full', member: 'Yoon', anchor: 9.08 },
          { id: 'vKcSTBikn4g', type: 'single_full', member: 'J', anchor: 9.09 },
        ],
      },
    ],
  },
];

export default IXVXStore;
